/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.internalFrame;

import proracun.ProracunBrSarzi;
import constatnt.Image;
import constatnt.LabelText;
import dbService.OtpremaService;
import dbService.RecepturaService;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import pogon.Pogon;
import pogon.osnova2.Preddozator;
import komandniProzori.KomandniProzorFrekfrentni;
import utils.Convert;
import utils.MousePoint;
import netvision.NetVision;
import pogon.osnova.Digitalac;
import komandniProzori.KomandniProzorPrekidac;
import komandniProzori.KomandniProzorTaster;
import komandniProzori.KomandniProzorTasterSaPolozajima;
import komandniProzori.KomandniProzorZadavanje;
import pogon.osnova2.AnalognaZadataIzdata;
import pogon.osnova2.TezineDvaRegistra;

/**
 *
 * @author Branko
 */
public class InternalFrameGlavnaSlika2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame1
     *
     * @param pogon
     * @param recepturaDb
     * @param otpremaDb
     * @param proracunKomponenti
     * @param img
     */
    public InternalFrameGlavnaSlika2(Pogon pogon, RecepturaService recepturaDb,
            OtpremaService otpremaDb, ProracunBrSarzi proracunKomponenti,  Image img) {
        initComponents();
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.img = img;
        this.pogon = pogon;
        this.recepturaDb = recepturaDb;
        this.otpremaDb = otpremaDb;
        this.proracunKomponenti = proracunKomponenti;
        initMinMax();
        initTimer();

        getReceptureZaComboBoxFrekfrentni();
        getReceptureZaComboBoxKomponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupIzborSilosa = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonStartKorpe = new javax.swing.JButton();
        jButtonStartLevo = new javax.swing.JButton();
        jButtonPromenaSmeraKorpe = new javax.swing.JButton();
        jButtonPromenaBrzineKorpe = new javax.swing.JButton();
        jButtonStartFrReg = new javax.swing.JButton();
        jButtonStartDesno = new javax.swing.JButton();
        jButtonPraznjenjeVagona = new javax.swing.JButton();
        jButtonStartDizni = new javax.swing.JButton();
        jButtonStartDizniKorpe = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonStartCiklusaKorpe = new javax.swing.JButton();
        jButtonStartCiklusaVagona = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonRad = new javax.swing.JToggleButton();
        ButtonOtprasivanje = new javax.swing.JToggleButton();
        ButtonSusara = new javax.swing.JToggleButton();
        ButtonVelikiGorionik = new javax.swing.JToggleButton();
        ButtonGorionikNaKanalu = new javax.swing.JToggleButton();
        ButtonPreddozator = new javax.swing.JToggleButton();
        ButtonMesalica = new javax.swing.JToggleButton();
        ButtonProizvodnjaAsfalta = new javax.swing.JToggleButton();
        jButtonTransport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        opisZadato = new javax.swing.JLabel();
        opisIzdato = new javax.swing.JLabel();
        opisHeader0_2 = new javax.swing.JLabel();
        opisHeader2_4 = new javax.swing.JLabel();
        opisHeader4_8 = new javax.swing.JLabel();
        opisHeaderRA = new javax.swing.JLabel();
        headerZadatoAgr1 = new javax.swing.JLabel();
        headerIzdatoAgr1 = new javax.swing.JLabel();
        headerZadatoAgr2 = new javax.swing.JLabel();
        headerIzdatoAgr2 = new javax.swing.JLabel();
        headerZadatoAgr3 = new javax.swing.JLabel();
        headerIzdatoAgr3 = new javax.swing.JLabel();
        MWheaderZadatoRA = new javax.swing.JLabel();
        MWheaderIzdatoRA = new javax.swing.JLabel();
        opisHeaderF1 = new javax.swing.JLabel();
        headerZadatoFKup = new javax.swing.JLabel();
        headerIzdatoFKup = new javax.swing.JLabel();
        opisHeaderF2 = new javax.swing.JLabel();
        headerZadatoFSop = new javax.swing.JLabel();
        headerIzdatoSop = new javax.swing.JLabel();
        opisHeader8_16 = new javax.swing.JLabel();
        headerZadatoAgr4 = new javax.swing.JLabel();
        headerIzdatoAgr4 = new javax.swing.JLabel();
        opisHeader16_24 = new javax.swing.JLabel();
        headerZadatoAgr5 = new javax.swing.JLabel();
        headerIzdatoAgr5 = new javax.swing.JLabel();
        opisHeader24_32 = new javax.swing.JLabel();
        headerZadatoAgr6 = new javax.swing.JLabel();
        headerIzdatoAgr6 = new javax.swing.JLabel();
        opisHeaderF7 = new javax.swing.JLabel();
        headerZadatoAgr7 = new javax.swing.JLabel();
        headerIzdatoAgr7 = new javax.swing.JLabel();
        opisHeaderB1 = new javax.swing.JLabel();
        headerZadatoBit = new javax.swing.JLabel();
        headerIzdatoBit = new javax.swing.JLabel();
        opisHeaderRA1 = new javax.swing.JLabel();
        headerZadatoBrSarzi = new javax.swing.JLabel();
        headerIzdatoBrSarzi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        opisHeaderRA2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxRecepturaKomponente = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        zadataKolicina = new javax.swing.JSpinner();
        jButtonRecepturaPrihvati = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxRecepturaFrekfrentni = new javax.swing.JComboBox<>();
        jButtonRecepturaPrihvati1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jToggleButtonSilos1 = new javax.swing.JToggleButton();
        jToggleButtonSilos2 = new javax.swing.JToggleButton();
        jToggleButtonSilos3 = new javax.swing.JToggleButton();
        jToggleButtonSilos4 = new javax.swing.JToggleButton();
        jToggleButtonSilos5 = new javax.swing.JToggleButton();
        jToggleIberVagon = new javax.swing.JToggleButton();
        jButtonGrejanjeVagona = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonSkretnicaVagon1 = new javax.swing.JButton();
        jButtonSkretnicaIber1 = new javax.swing.JButton();
        jButtonSkretnicaVagon2 = new javax.swing.JButton();
        jButtonSkretnicaIber2 = new javax.swing.JButton();
        jButtonSkretnica = new javax.swing.JButton();

        jPanel1.setLayout(null);

        jButtonExit.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        jButtonExit.setText("X");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonExitMousePressed(evt);
            }
        });
        jPanel1.add(jButtonExit);
        jButtonExit.setBounds(1883, 0, 40, 40);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Rucni rad korpe i vagona"));
        jPanel7.setOpaque(false);

        jButtonStartKorpe.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartKorpe.setText("Start korpe");
        jButtonStartKorpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartKorpeActionPerformed(evt);
            }
        });

        jButtonStartLevo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartLevo.setText("Start levo");
        jButtonStartLevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartLevoActionPerformed(evt);
            }
        });

        jButtonPromenaSmeraKorpe.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonPromenaSmeraKorpe.setText("Promena smera korpe");
        jButtonPromenaSmeraKorpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromenaSmeraKorpeActionPerformed(evt);
            }
        });

        jButtonPromenaBrzineKorpe.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonPromenaBrzineKorpe.setText("Promena brzine korpe");
        jButtonPromenaBrzineKorpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromenaBrzineKorpeActionPerformed(evt);
            }
        });

        jButtonStartFrReg.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartFrReg.setText("Start frekventnog regulatora");
        jButtonStartFrReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartFrRegActionPerformed(evt);
            }
        });

        jButtonStartDesno.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartDesno.setText("Start desno");
        jButtonStartDesno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartDesnoActionPerformed(evt);
            }
        });

        jButtonPraznjenjeVagona.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonPraznjenjeVagona.setText("Praznjenje vagona");
        jButtonPraznjenjeVagona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPraznjenjeVagonaActionPerformed(evt);
            }
        });

        jButtonStartDizni.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartDizni.setText("Start dizni vagona");
        jButtonStartDizni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartDizniActionPerformed(evt);
            }
        });

        jButtonStartDizniKorpe.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartDizniKorpe.setText("Start dizni korpi");
        jButtonStartDizniKorpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartDizniKorpeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonStartFrReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButtonStartKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStartLevo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButtonPromenaSmeraKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStartDesno, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPromenaBrzineKorpe, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jButtonStartDizniKorpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonStartDizni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPraznjenjeVagona, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartLevo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPromenaSmeraKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartDesno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPromenaBrzineKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPraznjenjeVagona, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartDizni, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartDizniKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStartFrReg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 710, 430, 270);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Automatski rad korpe i vagona"));
        jPanel6.setOpaque(false);

        jButtonStartCiklusaKorpe.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartCiklusaKorpe.setText("Start ciklusa korpe");
        jButtonStartCiklusaKorpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartCiklusaKorpeActionPerformed(evt);
            }
        });

        jButtonStartCiklusaVagona.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonStartCiklusaVagona.setText("Start ciklusa vagona");
        jButtonStartCiklusaVagona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartCiklusaVagonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonStartCiklusaKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStartCiklusaVagona, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartCiklusaKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartCiklusaVagona, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 630, 430, 80);

        jPanel2.setBackground(new java.awt.Color(198, 211, 237));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonRad.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonRad.setText("1");
        ButtonRad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonRadMousePressed(evt);
            }
        });

        ButtonOtprasivanje.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonOtprasivanje.setText("2");
        ButtonOtprasivanje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonOtprasivanjeMousePressed(evt);
            }
        });

        ButtonSusara.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonSusara.setText("4");
        ButtonSusara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonSusaraMousePressed(evt);
            }
        });

        ButtonVelikiGorionik.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonVelikiGorionik.setText("5");
        ButtonVelikiGorionik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonVelikiGorionikMousePressed(evt);
            }
        });

        ButtonGorionikNaKanalu.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonGorionikNaKanalu.setText("6");
        ButtonGorionikNaKanalu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonGorionikNaKanaluMousePressed(evt);
            }
        });

        ButtonPreddozator.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonPreddozator.setText("7");
        ButtonPreddozator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonPreddozatorMousePressed(evt);
            }
        });

        ButtonMesalica.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonMesalica.setText("8");
        ButtonMesalica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonMesalicaMousePressed(evt);
            }
        });

        ButtonProizvodnjaAsfalta.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ButtonProizvodnjaAsfalta.setText("9");
        ButtonProizvodnjaAsfalta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonProizvodnjaAsfaltaMousePressed(evt);
            }
        });

        jButtonTransport.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButtonTransport.setText("3");
        jButtonTransport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTransportMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonTransportMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonRad, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
            .addComponent(ButtonOtprasivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonSusara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonVelikiGorionik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonGorionikNaKanalu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonPreddozator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonMesalica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonProizvodnjaAsfalta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonTransport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonRad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonOtprasivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransport, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSusara, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonVelikiGorionik, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonGorionikNaKanalu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPreddozator, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonMesalica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonProizvodnjaAsfalta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 100, 430, 525);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jPanel3.setLayout(null);

        opisZadato.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisZadato.setForeground(new java.awt.Color(102, 102, 102));
        opisZadato.setText("Zadato");
        jPanel3.add(opisZadato);
        opisZadato.setBounds(10, 30, 60, 19);

        opisIzdato.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisIzdato.setForeground(new java.awt.Color(102, 102, 102));
        opisIzdato.setText("Izdato");
        jPanel3.add(opisIzdato);
        opisIzdato.setBounds(10, 60, 60, 19);

        opisHeader0_2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeader0_2.setForeground(new java.awt.Color(102, 102, 102));
        opisHeader0_2.setText("0-32 mm");
        jPanel3.add(opisHeader0_2);
        opisHeader0_2.setBounds(260, 0, 60, 19);

        opisHeader2_4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeader2_4.setForeground(new java.awt.Color(102, 102, 102));
        opisHeader2_4.setText("0-4 mm");
        jPanel3.add(opisHeader2_4);
        opisHeader2_4.setBounds(340, 0, 60, 19);

        opisHeader4_8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeader4_8.setForeground(new java.awt.Color(102, 102, 102));
        opisHeader4_8.setText("4-8 mm");
        jPanel3.add(opisHeader4_8);
        opisHeader4_8.setBounds(420, 0, 60, 19);

        opisHeaderRA.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderRA.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderRA.setText("RA");
        jPanel3.add(opisHeaderRA);
        opisHeaderRA.setBounds(930, 0, 60, 19);

        headerZadatoAgr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr1.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr1.setText("0");
        headerZadatoAgr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr1MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr1);
        headerZadatoAgr1.setBounds(260, 30, 60, 19);

        headerIzdatoAgr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr1.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr1.setText("0");
        jPanel3.add(headerIzdatoAgr1);
        headerIzdatoAgr1.setBounds(260, 60, 60, 19);

        headerZadatoAgr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr2.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr2.setText("0");
        headerZadatoAgr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr2MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr2);
        headerZadatoAgr2.setBounds(340, 30, 60, 19);

        headerIzdatoAgr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr2.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr2.setText("0");
        jPanel3.add(headerIzdatoAgr2);
        headerIzdatoAgr2.setBounds(340, 60, 60, 19);

        headerZadatoAgr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr3.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr3.setText("0");
        headerZadatoAgr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr3MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr3);
        headerZadatoAgr3.setBounds(420, 30, 60, 19);

        headerIzdatoAgr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr3.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr3.setText("0");
        jPanel3.add(headerIzdatoAgr3);
        headerIzdatoAgr3.setBounds(420, 60, 60, 19);

        MWheaderZadatoRA.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        MWheaderZadatoRA.setForeground(new java.awt.Color(102, 102, 102));
        MWheaderZadatoRA.setText("0");
        jPanel3.add(MWheaderZadatoRA);
        MWheaderZadatoRA.setBounds(930, 30, 60, 19);

        MWheaderIzdatoRA.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        MWheaderIzdatoRA.setForeground(new java.awt.Color(102, 102, 102));
        MWheaderIzdatoRA.setText("0");
        jPanel3.add(MWheaderIzdatoRA);
        MWheaderIzdatoRA.setBounds(930, 60, 60, 19);

        opisHeaderF1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderF1.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderF1.setText("F kup");
        jPanel3.add(opisHeaderF1);
        opisHeaderF1.setBounds(100, 0, 60, 19);

        headerZadatoFKup.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoFKup.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoFKup.setText("0");
        headerZadatoFKup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoFKupMousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoFKup);
        headerZadatoFKup.setBounds(100, 30, 60, 19);

        headerIzdatoFKup.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoFKup.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoFKup.setText("0");
        jPanel3.add(headerIzdatoFKup);
        headerIzdatoFKup.setBounds(100, 60, 60, 19);

        opisHeaderF2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderF2.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderF2.setText("F sop");
        jPanel3.add(opisHeaderF2);
        opisHeaderF2.setBounds(180, 0, 60, 19);

        headerZadatoFSop.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoFSop.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoFSop.setText("0");
        headerZadatoFSop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoFSopMousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoFSop);
        headerZadatoFSop.setBounds(180, 30, 60, 19);

        headerIzdatoSop.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoSop.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoSop.setText("0");
        jPanel3.add(headerIzdatoSop);
        headerIzdatoSop.setBounds(180, 60, 60, 19);

        opisHeader8_16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeader8_16.setForeground(new java.awt.Color(102, 102, 102));
        opisHeader8_16.setText("8-11 mm");
        jPanel3.add(opisHeader8_16);
        opisHeader8_16.setBounds(490, 0, 60, 19);

        headerZadatoAgr4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr4.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr4.setText("0");
        headerZadatoAgr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr4MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr4);
        headerZadatoAgr4.setBounds(490, 30, 60, 19);

        headerIzdatoAgr4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr4.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr4.setText("0");
        jPanel3.add(headerIzdatoAgr4);
        headerIzdatoAgr4.setBounds(490, 60, 60, 19);

        opisHeader16_24.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeader16_24.setForeground(new java.awt.Color(102, 102, 102));
        opisHeader16_24.setText("11-16 mm");
        jPanel3.add(opisHeader16_24);
        opisHeader16_24.setBounds(570, 0, 79, 19);

        headerZadatoAgr5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr5.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr5.setText("0");
        headerZadatoAgr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr5MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr5);
        headerZadatoAgr5.setBounds(570, 30, 79, 19);

        headerIzdatoAgr5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr5.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr5.setText("0");
        jPanel3.add(headerIzdatoAgr5);
        headerIzdatoAgr5.setBounds(570, 60, 79, 19);

        opisHeader24_32.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeader24_32.setForeground(new java.awt.Color(102, 102, 102));
        opisHeader24_32.setText("16-22 mm");
        jPanel3.add(opisHeader24_32);
        opisHeader24_32.setBounds(670, 0, 79, 19);

        headerZadatoAgr6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr6.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr6.setText("0");
        headerZadatoAgr6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr6MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr6);
        headerZadatoAgr6.setBounds(670, 30, 79, 19);

        headerIzdatoAgr6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr6.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr6.setText("0");
        jPanel3.add(headerIzdatoAgr6);
        headerIzdatoAgr6.setBounds(670, 60, 79, 19);

        opisHeaderF7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderF7.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderF7.setText("16-32 mm");
        jPanel3.add(opisHeaderF7);
        opisHeaderF7.setBounds(770, 0, 70, 19);

        headerZadatoAgr7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoAgr7.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoAgr7.setText("0");
        headerZadatoAgr7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoAgr7MousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoAgr7);
        headerZadatoAgr7.setBounds(770, 30, 60, 19);

        headerIzdatoAgr7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoAgr7.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoAgr7.setText("0");
        jPanel3.add(headerIzdatoAgr7);
        headerIzdatoAgr7.setBounds(770, 60, 60, 19);

        opisHeaderB1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderB1.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderB1.setText("Bit");
        jPanel3.add(opisHeaderB1);
        opisHeaderB1.setBounds(860, 0, 60, 19);

        headerZadatoBit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoBit.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoBit.setText("0");
        headerZadatoBit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerZadatoBitMousePressed(evt);
            }
        });
        jPanel3.add(headerZadatoBit);
        headerZadatoBit.setBounds(860, 30, 60, 19);

        headerIzdatoBit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoBit.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoBit.setText("0");
        jPanel3.add(headerIzdatoBit);
        headerIzdatoBit.setBounds(860, 60, 60, 19);

        opisHeaderRA1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderRA1.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderRA1.setText("Reset");
        jPanel3.add(opisHeaderRA1);
        opisHeaderRA1.setBounds(1130, 0, 60, 20);

        headerZadatoBrSarzi.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerZadatoBrSarzi.setForeground(new java.awt.Color(102, 102, 102));
        headerZadatoBrSarzi.setText("0");
        jPanel3.add(headerZadatoBrSarzi);
        headerZadatoBrSarzi.setBounds(1020, 30, 60, 19);

        headerIzdatoBrSarzi.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        headerIzdatoBrSarzi.setForeground(new java.awt.Color(102, 102, 102));
        headerIzdatoBrSarzi.setText("0");
        jPanel3.add(headerIzdatoBrSarzi);
        headerIzdatoBrSarzi.setBounds(1020, 60, 60, 19);

        jButton1.setText("Urađenih sarzi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1100, 58, 120, 30);

        opisHeaderRA2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        opisHeaderRA2.setForeground(new java.awt.Color(102, 102, 102));
        opisHeaderRA2.setText("Br Sarzi");
        jPanel3.add(opisHeaderRA2);
        opisHeaderRA2.setBounds(1020, 0, 60, 19);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1920, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Receptura za proizvodnju asfalta"));

        jComboBoxRecepturaKomponente.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jComboBoxRecepturaKomponente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRecepturaKomponente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxRecepturaKomponentePopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Količina:");

        zadataKolicina.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99000000, 1));

        jButtonRecepturaPrihvati.setText("Pokreni");
        jButtonRecepturaPrihvati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecepturaPrihvatiActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Kg.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonRecepturaPrihvati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(zadataKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addComponent(jComboBoxRecepturaKomponente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jComboBoxRecepturaKomponente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zadataKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRecepturaPrihvati, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(430, 100, 360, 170);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Receptura preddozatora"));

        jComboBoxRecepturaFrekfrentni.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jComboBoxRecepturaFrekfrentni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRecepturaFrekfrentni.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxRecepturaFrekfrentniPopupMenuWillBecomeVisible(evt);
            }
        });

        jButtonRecepturaPrihvati1.setText("Prihvati");
        jButtonRecepturaPrihvati1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecepturaPrihvati1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonRecepturaPrihvati1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxRecepturaFrekfrentni, 0, 332, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jComboBoxRecepturaFrekfrentni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecepturaPrihvati1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(790, 100, 360, 140);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Izbor silosa"));

        buttonGroupIzborSilosa.add(jToggleButtonSilos1);
        jToggleButtonSilos1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jToggleButtonSilos1.setText("1");
        jToggleButtonSilos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSilos1ActionPerformed(evt);
            }
        });

        buttonGroupIzborSilosa.add(jToggleButtonSilos2);
        jToggleButtonSilos2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jToggleButtonSilos2.setText("2");
        jToggleButtonSilos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSilos2ActionPerformed(evt);
            }
        });

        buttonGroupIzborSilosa.add(jToggleButtonSilos3);
        jToggleButtonSilos3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jToggleButtonSilos3.setText("3");
        jToggleButtonSilos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSilos3ActionPerformed(evt);
            }
        });

        buttonGroupIzborSilosa.add(jToggleButtonSilos4);
        jToggleButtonSilos4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jToggleButtonSilos4.setText("4");
        jToggleButtonSilos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSilos4ActionPerformed(evt);
            }
        });

        buttonGroupIzborSilosa.add(jToggleButtonSilos5);
        jToggleButtonSilos5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jToggleButtonSilos5.setText("5");
        jToggleButtonSilos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSilos5ActionPerformed(evt);
            }
        });

        jToggleIberVagon.setText("Iber");
        jToggleIberVagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleIberVagonActionPerformed(evt);
            }
        });

        jButtonGrejanjeVagona.setText("Grejanje usta vagona");
        jButtonGrejanjeVagona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrejanjeVagonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jToggleButtonSilos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jToggleButtonSilos2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jToggleButtonSilos3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jToggleButtonSilos4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jToggleButtonSilos5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleIberVagon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGrejanjeVagona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonSilos1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSilos2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSilos3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSilos4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonSilos5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleIberVagon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButtonGrejanjeVagona, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(440, 630, 490, 200);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Upravljanje skretnicom"));

        jButtonSkretnicaVagon1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSkretnicaVagon1.setText("Vagon");

        jButtonSkretnicaIber1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSkretnicaIber1.setText("Iber");

        jButtonSkretnicaVagon2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSkretnicaVagon2.setText("Vagon");

        jButtonSkretnicaIber2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSkretnicaIber2.setText("Iber");

        jButtonSkretnica.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSkretnica.setText("Skretnica");
        jButtonSkretnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSkretnicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSkretnicaVagon1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSkretnicaIber1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSkretnica, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSkretnicaVagon2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSkretnicaIber2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jButtonSkretnicaVagon1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSkretnicaIber1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButtonSkretnicaVagon2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSkretnicaIber2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonSkretnica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(440, 830, 490, 150);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMousePressed
        timerStop();
        this.dispose();
    }//GEN-LAST:event_jButtonExitMousePressed

    private void ButtonRadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRadMousePressed
        taster(!pogon.getGrupakomandi().getRad().getKomanda().isVrednost(), pogon.getGrupakomandi().getRad().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonRadMousePressed

    private void ButtonOtprasivanjeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOtprasivanjeMousePressed
        taster(!pogon.getGrupakomandi().getOtprasivanje().getKomanda().isVrednost(), pogon.getGrupakomandi().getOtprasivanje().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonOtprasivanjeMousePressed

    private void ButtonSusaraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSusaraMousePressed
        taster(!pogon.getGrupakomandi().getSusara().getKomanda().isVrednost(), pogon.getGrupakomandi().getSusara().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonSusaraMousePressed

    private void ButtonVelikiGorionikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVelikiGorionikMousePressed
        taster(!pogon.getGrupakomandi().getVelikiGorionik().getKomanda().isVrednost(), pogon.getGrupakomandi().getVelikiGorionik().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonVelikiGorionikMousePressed

    private void ButtonGorionikNaKanaluMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonGorionikNaKanaluMousePressed
        taster(!pogon.getGrupakomandi().getGorionikNaKanalu().getKomanda().isVrednost(), pogon.getGrupakomandi().getGorionikNaKanalu().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonGorionikNaKanaluMousePressed

    private void ButtonPreddozatorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPreddozatorMousePressed
        taster(!pogon.getGrupakomandi().getPredozator().getKomanda().isVrednost(), pogon.getGrupakomandi().getPredozator().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonPreddozatorMousePressed

    private void ButtonMesalicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMesalicaMousePressed
        taster(!pogon.getGrupakomandi().getMesalica().getKomanda().isVrednost(), pogon.getGrupakomandi().getMesalica().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonMesalicaMousePressed

    private void ButtonProizvodnjaAsfaltaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonProizvodnjaAsfaltaMousePressed
        taster(!pogon.getGrupakomandi().getProizvodnjaAsfalta().getKomanda().isVrednost(), pogon.getGrupakomandi().getProizvodnjaAsfalta().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_ButtonProizvodnjaAsfaltaMousePressed

    private void jComboBoxRecepturaKomponentePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxRecepturaKomponentePopupMenuWillBecomeVisible
        getReceptureZaComboBoxKomponente();
    }//GEN-LAST:event_jComboBoxRecepturaKomponentePopupMenuWillBecomeVisible

    private void jButtonRecepturaPrihvatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecepturaPrihvatiActionPerformed
        db.Receptura receptura = recepture.get(jComboBoxRecepturaKomponente.getSelectedIndex());
        if (JOptionPane.showConfirmDialog(this, "Da li želite da kreirate novu otpremu?", "Obavestenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            if (proracunKomponenti.calculateBrSarzi(
                    Integer.valueOf(zadataKolicina.getValue().toString()),
                    pogon.getParametri().getKapacitetMesalice(),
                    receptura)) {

                otpremaDb.addOprema(receptura.getReceptura(), "Vozac", "Vozilo", 
                        "Gradiliste", "Kupac", Integer.parseInt(zadataKolicina.getValue().toString()));

                pogon.getZadatoBrSarzi().setVrednost(proracunKomponenti.getZadatiBrojSarzi());
                headerZadatoBrSarzi.setText(Integer.toString(pogon.getZadatoBrSarzi().getVrednost()));
                setParametars();
                setPreddozatorePoRecepturi(receptura);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Pokusajte ponovo");
        }


    }//GEN-LAST:event_jButtonRecepturaPrihvatiActionPerformed

    private void jButtonRecepturaPrihvati1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecepturaPrihvati1ActionPerformed
        db.Receptura recepturaFr = recepture.get(jComboBoxRecepturaFrekfrentni.getSelectedIndex());
        setParametarsPreddozatori(recepturaFr);
        setPreddozatorePoRecepturi(recepturaFr);
    }//GEN-LAST:event_jButtonRecepturaPrihvati1ActionPerformed

    private void jComboBoxRecepturaFrekfrentniPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxRecepturaFrekfrentniPopupMenuWillBecomeVisible
        getReceptureZaComboBoxFrekfrentni();
    }//GEN-LAST:event_jComboBoxRecepturaFrekfrentniPopupMenuWillBecomeVisible

    private void jButtonStartCiklusaKorpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartCiklusaKorpeActionPerformed
        ciklusKorpe = 10;
        ciklusKorpeBool = true;
        NetVision.mb.writeMX(true, pogon.getKorpaVagon().getStartCiklusaKorpe().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartCiklusaKorpeActionPerformed

    private void jButtonStartCiklusaVagonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartCiklusaVagonaActionPerformed
        ciklusVagona = 10;
        ciklusVagonaBool = true;
        NetVision.mb.writeMX(true, pogon.getKorpaVagon().getStartCiklusaVagona().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartCiklusaVagonaActionPerformed

    private void jButtonStartKorpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartKorpeActionPerformed
         NetVision.mb.writeMX(!pogon.getKorpaVagon().getStartKorpe().isVrednost(), pogon.getKorpaVagon().getStartKorpe().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartKorpeActionPerformed

    private void jButtonPromenaSmeraKorpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromenaSmeraKorpeActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getPromenaSmeraKorpe().isVrednost(), pogon.getKorpaVagon().getPromenaSmeraKorpe().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonPromenaSmeraKorpeActionPerformed

    private void jButtonPromenaBrzineKorpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromenaBrzineKorpeActionPerformed
       NetVision.mb.writeMX(!pogon.getKorpaVagon().getPromenaBrzinaKorpe().isVrednost(), pogon.getKorpaVagon().getPromenaBrzinaKorpe().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonPromenaBrzineKorpeActionPerformed

    private void jButtonStartFrRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartFrRegActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getStartFrekfrentnogReg().isVrednost(), pogon.getKorpaVagon().getStartFrekfrentnogReg().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartFrRegActionPerformed

    private void jButtonStartLevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartLevoActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getStartLevo().isVrednost(), pogon.getKorpaVagon().getStartLevo().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartLevoActionPerformed

    private void jButtonStartDesnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartDesnoActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getStartDesno().isVrednost(), pogon.getKorpaVagon().getStartDesno().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartDesnoActionPerformed

    private void jButtonPraznjenjeVagonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPraznjenjeVagonaActionPerformed
       NetVision.mb.writeMX(!pogon.getKorpaVagon().getPraznjenjeVagona().isVrednost(), pogon.getKorpaVagon().getPraznjenjeVagona().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonPraznjenjeVagonaActionPerformed

    private void jButtonStartDizniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartDizniActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getStartDizniVagona().isVrednost(), pogon.getKorpaVagon().getStartDizniVagona().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartDizniActionPerformed

    private void jToggleButtonSilos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSilos1ActionPerformed
        NetVision.mb.writeMW(1, pogon.getKorpaVagon().getSelectSilos().getAdresaVrednosti());
    }//GEN-LAST:event_jToggleButtonSilos1ActionPerformed

    private void jToggleButtonSilos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSilos2ActionPerformed
        NetVision.mb.writeMW(2, pogon.getKorpaVagon().getSelectSilos().getAdresaVrednosti());
    }//GEN-LAST:event_jToggleButtonSilos2ActionPerformed

    private void jToggleButtonSilos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSilos3ActionPerformed
        NetVision.mb.writeMW(3, pogon.getKorpaVagon().getSelectSilos().getAdresaVrednosti());
    }//GEN-LAST:event_jToggleButtonSilos3ActionPerformed

    private void jToggleButtonSilos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSilos4ActionPerformed
        NetVision.mb.writeMW(4, pogon.getKorpaVagon().getSelectSilos().getAdresaVrednosti());
    }//GEN-LAST:event_jToggleButtonSilos4ActionPerformed

    private void jToggleButtonSilos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSilos5ActionPerformed
        NetVision.mb.writeMW(5, pogon.getKorpaVagon().getSelectSilos().getAdresaVrednosti());
    }//GEN-LAST:event_jToggleButtonSilos5ActionPerformed

    private void jToggleIberVagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleIberVagonActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getIberVagona().isVrednost(), pogon.getKorpaVagon().getIberVagona().getAdresaVrednosti());
    }//GEN-LAST:event_jToggleIberVagonActionPerformed

    private void jButtonStartDizniKorpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartDizniKorpeActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getStartDizniKorpe().isVrednost(), pogon.getKorpaVagon().getStartDizniKorpe().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonStartDizniKorpeActionPerformed

    private void jButtonGrejanjeVagonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrejanjeVagonaActionPerformed
        NetVision.mb.writeMX(!pogon.getKorpaVagon().getGrejanjeUstavagona().isVrednost(), pogon.getKorpaVagon().getGrejanjeUstavagona().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonGrejanjeVagonaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NetVision.mb.writeMW(0, pogon.getIzdatoBrSarzi().getAdresaVrednosti());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonTransportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTransportMousePressed
        taster(true, pogon.getGrupakomandi().getTransport().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonTransportMousePressed

    private void jButtonTransportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTransportMouseReleased
        taster(false, pogon.getGrupakomandi().getTransport().getKomanda().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonTransportMouseReleased

    private void headerZadatoFKupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoFKupMousePressed
        showScreen(screenZadavanjeFKup, pogon.getFiler().getKupovni());
    }//GEN-LAST:event_headerZadatoFKupMousePressed

    private void headerZadatoFSopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoFSopMousePressed
        showScreen(screenZadavanjeFSop, pogon.getFiler().getSopstveni());
    }//GEN-LAST:event_headerZadatoFSopMousePressed

    private void headerZadatoAgr1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr1MousePressed
        showScreen(screenZadavanje0_32, pogon.getAgregat().getDoz1());
    }//GEN-LAST:event_headerZadatoAgr1MousePressed

    private void headerZadatoAgr2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr2MousePressed
        showScreen(screenZadavanje0_4, pogon.getAgregat().getDoz2());
    }//GEN-LAST:event_headerZadatoAgr2MousePressed

    private void headerZadatoAgr3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr3MousePressed
        showScreen(screenZadavanje4_8, pogon.getAgregat().getDoz3());
    }//GEN-LAST:event_headerZadatoAgr3MousePressed

    private void headerZadatoAgr4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr4MousePressed
        showScreen(screenZadavanje8_11, pogon.getAgregat().getDoz4());
    }//GEN-LAST:event_headerZadatoAgr4MousePressed

    private void headerZadatoAgr5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr5MousePressed
        showScreen(screenZadavanje11_16, pogon.getAgregat().getDoz5());
    }//GEN-LAST:event_headerZadatoAgr5MousePressed

    private void headerZadatoAgr6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr6MousePressed
        showScreen(screenZadavanje16_22, pogon.getAgregat().getDoz6());
    }//GEN-LAST:event_headerZadatoAgr6MousePressed

    private void headerZadatoAgr7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoAgr7MousePressed
        showScreen(screenZadavanje16_32, pogon.getAgregat().getDoz7());
    }//GEN-LAST:event_headerZadatoAgr7MousePressed

    private void headerZadatoBitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerZadatoBitMousePressed
        showScreen(screenZadavanjeBitumen, pogon.getBitumen().getKolicine());
    }//GEN-LAST:event_headerZadatoBitMousePressed

    private void jButtonSkretnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkretnicaActionPerformed
        //pogon.getSkretnica().getSkretnicaUpravljanje().setVrednost(!pogon.getSkretnica().getSkretnicaUpravljanje().isVrednost());
        NetVision.mb.writeMX(!pogon.getSkretnica().getSkretnicaUpravljanje().isVrednost(), pogon.getSkretnica().getSkretnicaUpravljanje().getAdresaVrednosti());
    }//GEN-LAST:event_jButtonSkretnicaActionPerformed

    private void getReceptureZaComboBoxKomponente() {
        recepture = recepturaDb.getReceptiOrderId();
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxRecepturaKomponente.getModel();

        // removing old data
        model.removeAllElements();
        for (int i = 0; i < recepture.size(); i++) {
            model.addElement(recepture.get(i).getReceptura());
        }
        // setting model with new data
        jComboBoxRecepturaKomponente.setModel(model);
    }
    
    private void getReceptureZaComboBoxFrekfrentni(){
        recepture = recepturaDb.getReceptiOrderId();
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxRecepturaFrekfrentni.getModel();
        // removing old data
        model.removeAllElements();
        for (int i = 0; i < recepture.size(); i++) {
            model.addElement(recepture.get(i).getReceptura());
        }
        // setting model with new data
        jComboBoxRecepturaFrekfrentni.setModel(model);       
    }

    private void initTimer() {
        timer = new Timer(300, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                refreshGrupaKomandi1();
                refreshZadatoIzdato1();
                saveChangeFrequency();
                enableButton();
                refreshKorpaVagon();
                selectSilos();
                hold3sec();
                refreshSkretnica();
            }
        });
    }

    
    private void refreshSkretnica(){
        LabelText.getColor(jButtonSkretnica, pogon.getSkretnica().getSkretnicaUpravljanje());
        LabelText.getColor(jButtonSkretnicaVagon1, pogon.getSkretnica().getSkretnicaVagon1());
        LabelText.getColor(jButtonSkretnicaVagon2, pogon.getSkretnica().getSkretnicaVagon2());
        LabelText.getColor(jButtonSkretnicaIber1, pogon.getSkretnica().getSkretnicaIber1());
        LabelText.getColor(jButtonSkretnicaIber2, pogon.getSkretnica().getSkretnicaIber2());
    }
    
    private void refreshGrupaKomandi1() {
        LabelText.getText(ButtonRad, pogon.getGrupakomandi().getRad());
        LabelText.getText(ButtonOtprasivanje, pogon.getGrupakomandi().getOtprasivanje());
        LabelText.getText(jButtonTransport, pogon.getGrupakomandi().getTextTransport().getVrednost()); 
        LabelText.getText(ButtonSusara, pogon.getGrupakomandi().getSusara());
        LabelText.getText(ButtonVelikiGorionik, pogon.getGrupakomandi().getVelikiGorionik());
        LabelText.getText(ButtonGorionikNaKanalu, pogon.getGrupakomandi().getGorionikNaKanalu());
        LabelText.getText(ButtonPreddozator, pogon.getGrupakomandi().getPredozator());
        LabelText.getText(ButtonMesalica, pogon.getGrupakomandi().getMesalica());
        LabelText.getText(ButtonProizvodnjaAsfalta, pogon.getGrupakomandi().getProizvodnjaAsfalta());
    }
    
    private void refreshKorpaVagon(){
        LabelText.getColor(jButtonStartCiklusaKorpe, pogon.getKorpaVagon().getStartCiklusaKorpe());
        LabelText.getColor(jButtonStartCiklusaVagona, pogon.getKorpaVagon().getStartCiklusaVagona());
        
        LabelText.getColor(jButtonStartKorpe, pogon.getKorpaVagon().getStartKorpe());
        LabelText.getColor(jButtonPromenaSmeraKorpe, pogon.getKorpaVagon().getPromenaSmeraKorpe());
        LabelText.getColor(jButtonPromenaBrzineKorpe, pogon.getKorpaVagon().getPromenaBrzinaKorpe());
        LabelText.getColor(jButtonStartFrReg, pogon.getKorpaVagon().getStartFrekfrentnogReg());
        
        LabelText.getColor(jButtonStartLevo, pogon.getKorpaVagon().getStartLevo());
        LabelText.getColor(jButtonStartDesno, pogon.getKorpaVagon().getStartDesno());
        LabelText.getColor(jButtonPraznjenjeVagona, pogon.getKorpaVagon().getPraznjenjeVagona());
        LabelText.getColor(jButtonStartDizni, pogon.getKorpaVagon().getStartDizniVagona());
        LabelText.getColor(jButtonStartDizniKorpe, pogon.getKorpaVagon().getStartDizniKorpe());
        
        if(pogon.getKorpaVagon().getIberVagona().isVrednost()){
            jToggleIberVagon.setSelected(true);
            jToggleIberVagon.setText("Vagon");
        }else{
            jToggleIberVagon.setSelected(false);
            jToggleIberVagon.setText("Iber");
        }
        LabelText.getColor(jButtonGrejanjeVagona, pogon.getKorpaVagon().getGrejanjeUstavagona());
        
    }
    
    private void selectSilos(){
        switch (pogon.getKorpaVagon().getSelectSilos().getVrednost()){
            case 1:
                jToggleButtonSilos1.setSelected(true);
                jToggleButtonSilos1.setBackground(Color.GREEN);
                jToggleButtonSilos2.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos3.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos4.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos5.setBackground(Color.LIGHT_GRAY);
                break;
            case 2:
                jToggleButtonSilos2.setSelected(true);
                jToggleButtonSilos1.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos2.setBackground(Color.GREEN);
                jToggleButtonSilos3.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos4.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos5.setBackground(Color.LIGHT_GRAY);
                break;
            case 3:
                jToggleButtonSilos3.setSelected(true);
                jToggleButtonSilos1.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos2.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos3.setBackground(Color.GREEN);
                jToggleButtonSilos4.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos5.setBackground(Color.LIGHT_GRAY);
                break;
            case 4:
                jToggleButtonSilos4.setSelected(true);
                jToggleButtonSilos1.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos2.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos3.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos4.setBackground(Color.GREEN);
                jToggleButtonSilos5.setBackground(Color.LIGHT_GRAY);
                break;
            case 5:
                jToggleButtonSilos5.setSelected(true);
                jToggleButtonSilos1.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos2.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos3.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos4.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos5.setBackground(Color.GREEN);
                break;
            default:
                jToggleButtonSilos1.setSelected(false);
                jToggleButtonSilos2.setSelected(false);
                jToggleButtonSilos3.setSelected(false);
                jToggleButtonSilos4.setSelected(false);
                jToggleButtonSilos5.setSelected(false);
                
                jToggleButtonSilos1.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos2.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos3.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos4.setBackground(Color.LIGHT_GRAY);
                jToggleButtonSilos5.setBackground(Color.LIGHT_GRAY);
                
        }
    }

    private void refreshZadatoIzdato1() {
        headerZadatoAgr1.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz1().getZadata().getVrednost(), pogon.getAgregat().getDoz1().getBrDec()));
        headerZadatoAgr2.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz2().getZadata().getVrednost(), pogon.getAgregat().getDoz2().getBrDec()));
        headerZadatoAgr3.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz3().getZadata().getVrednost(), pogon.getAgregat().getDoz3().getBrDec()));
        headerZadatoAgr4.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz4().getZadata().getVrednost(), pogon.getAgregat().getDoz4().getBrDec()));
        headerZadatoAgr5.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz5().getZadata().getVrednost(), pogon.getAgregat().getDoz5().getBrDec()));
        headerZadatoAgr6.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz6().getZadata().getVrednost(), pogon.getAgregat().getDoz6().getBrDec()));
        headerZadatoAgr7.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz7().getZadata().getVrednost(), pogon.getAgregat().getDoz7().getBrDec()));
        headerZadatoFKup.setText(Convert.shiftPointUnsign(pogon.getFiler().getKupovni().getZadata().getVrednost(), pogon.getFiler().getKupovni().getBrDec()));
        headerZadatoFSop.setText(Convert.shiftPointUnsign(pogon.getFiler().getSopstveni().getZadata().getVrednost(), pogon.getFiler().getSopstveni().getBrDec()));
        headerZadatoBit.setText(Convert.shiftPointUnsign(pogon.getBitumen().getKolicine().getZadata().getVrednost(), pogon.getBitumen().getKolicine().getBrDec()));

        headerIzdatoBrSarzi.setText(Convert.shiftPointUnsign(pogon.getIzdatoBrSarzi().getVrednost(), pogon.getIzdatoBrSarzi().getBrojDecimala()));
        headerIzdatoAgr1.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz1().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz1().getBrDec()));
        headerIzdatoAgr2.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz2().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz2().getBrDec()));
        headerIzdatoAgr3.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz3().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz3().getBrDec()));
        headerIzdatoAgr4.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz4().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz4().getBrDec()));
        headerIzdatoAgr5.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz5().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz5().getBrDec()));
        headerIzdatoAgr6.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz6().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz6().getBrDec()));
        headerIzdatoAgr7.setText(Convert.shiftPointUnsign(pogon.getAgregat().getDoz7().getIzdozirana().getVrednost(), pogon.getAgregat().getDoz7().getBrDec()));
        headerIzdatoFKup.setText(Convert.shiftPointUnsign(pogon.getFiler().getKupovni().getIzdozirana().getVrednost(), pogon.getFiler().getKupovni().getBrDec()));
        headerIzdatoSop.setText(Convert.shiftPointUnsign(pogon.getFiler().getSopstveni().getIzdozirana().getVrednost(), pogon.getFiler().getSopstveni().getBrDec()));
        headerIzdatoBit.setText(Convert.shiftPointUnsign(pogon.getBitumen().getKolicine().getIzdozirana().getVrednost(), pogon.getBitumen().getKolicine().getBrDec()));
    }
    
    private void enableButton(){
        if(!pogon.getGrupakomandi().getRad().getKomanda().isVrednost()){
            jButtonStartCiklusaKorpe.setEnabled(false);
            jButtonStartCiklusaVagona.setEnabled(false);
            
            jButtonStartKorpe.setEnabled(true);
            jButtonPromenaSmeraKorpe.setEnabled(true);
            jButtonPromenaBrzineKorpe.setEnabled(true);
            jButtonStartFrReg.setEnabled(true);
            
            jButtonStartLevo.setEnabled(true);
            jButtonStartDesno.setEnabled(true);
            jButtonPraznjenjeVagona.setEnabled(true);
            jButtonStartDizni.setEnabled(true);
            jButtonStartDizniKorpe.setEnabled(true);
        }else{
            jButtonStartCiklusaKorpe.setEnabled(true);
            jButtonStartCiklusaVagona.setEnabled(true);
            
            jButtonStartKorpe.setEnabled(false);
            jButtonPromenaSmeraKorpe.setEnabled(false);
            jButtonPromenaBrzineKorpe.setEnabled(false);
            jButtonStartFrReg.setEnabled(true);
            
            jButtonStartLevo.setEnabled(false);
            jButtonStartDesno.setEnabled(false);
            jButtonPraznjenjeVagona.setEnabled(false);
            jButtonStartDizni.setEnabled(true);
            jButtonStartDizniKorpe.setEnabled(true);
        }
    }
    
    private void hold3sec(){
        if(ciklusKorpeBool){
         if(ciklusKorpe>0){
             ciklusKorpe--;
         }else{
            NetVision.mb.writeMX(false, pogon.getKorpaVagon().getStartCiklusaKorpe().getAdresaVrednosti());
            ciklusKorpeBool = false;
         }
        }
        if(ciklusVagonaBool){
         if(ciklusVagona>0){
             ciklusVagona--;
         }else{
            NetVision.mb.writeMX(false, pogon.getKorpaVagon().getStartCiklusaVagona().getAdresaVrednosti());
            ciklusVagonaBool = false;
         }
        }
           
    }

    

    private void initMinMax() {

    }

    public void timerStart() {
        timer.start();
    }

    public void timerStop() {
        timer.stop();
    }

    //Komandni prozor
    private KomandniProzorFrekfrentni showScreen(KomandniProzorFrekfrentni screen, Preddozator frekfrentni) {
        p = MousePoint.getMousePoint();
        if (screen == null) {
            screen = new KomandniProzorFrekfrentni(p.x, p.y, img, frekfrentni);
            screen.timerStart();
        }
        screen.timerStart();
        screen.setVisible(true);

        return screen;
    }

    private KomandniProzorTaster showScreen(KomandniProzorTaster screen, int tipSlike,
            String opis, Digitalac komanda, Digitalac potvrdaRada, Digitalac greska) {
        p = MousePoint.getMousePoint();
        if (screen == null) {
            screen = new KomandniProzorTaster(p.x, p.y, img, tipSlike, opis, komanda, potvrdaRada, greska);
            screen.timerStart();
        }
        screen.timerStart();
        screen.setVisible(true);

        return screen;
    }

    private KomandniProzorPrekidac showScreen(KomandniProzorPrekidac screen,
            int tipSlike, String opis, Digitalac komandaUkljuci, Digitalac komandaIskljuci,
            Digitalac komandaOtvoren, Digitalac komandaZatvoren,
            Digitalac potvrdaRadaL, Digitalac potvrdaRadaD, Digitalac greska) {
        p = MousePoint.getMousePoint();
        if (screen == null) {
            screen = new KomandniProzorPrekidac(p.x, p.y, img, tipSlike, opis,
                    komandaUkljuci, komandaIskljuci, komandaOtvoren, komandaZatvoren,
                    potvrdaRadaL, potvrdaRadaD, greska);
            screen.timerStart();
        }
        screen.timerStart();
        screen.setVisible(true);

        return screen;
    }

    private KomandniProzorTasterSaPolozajima showScreen(KomandniProzorTasterSaPolozajima screen,
            int tipSlike, String opis, Digitalac komanda, Digitalac potvrdaRada,
            Digitalac greska, Digitalac otvoren, Digitalac zatvoren) {
        p = MousePoint.getMousePoint();
        if (screen == null) {
            screen = new KomandniProzorTasterSaPolozajima(p.x, p.y, img, tipSlike, opis,
                    komanda, potvrdaRada, greska,
                    otvoren, zatvoren);
            screen.timerStart();
        }
        screen.timerStart();
        screen.setVisible(true);

        return screen;
    }
    
     private KomandniProzorZadavanje showScreen(KomandniProzorZadavanje screen, AnalognaZadataIzdata tezDvaReg) {
        p = MousePoint.getMousePoint();
        if (screen == null) {
            screen = new KomandniProzorZadavanje(p.x, p.y, tezDvaReg);
        }
        screen.timerStart();
        screen.setVisible(true);

        return screen;
    }

    private void setParametars() {
        int adresaAsfaltriranje = 200;  
       
        int[] podaciAsfalt = {
            proracunKomponenti.getFrakcija1(),
            proracunKomponenti.getFrakcija2(),
            proracunKomponenti.getFrakcija3(),
            proracunKomponenti.getFrakcija4(),
            proracunKomponenti.getFrakcija5(),
            proracunKomponenti.getFrakcija6(),
            proracunKomponenti.getFrakcija7(),
            proracunKomponenti.getFilerKupljen(),
            proracunKomponenti.getFilerSopstven(),
            proracunKomponenti.getBitumen()};
        
        
        NetVision.mb.writeMWs(podaciAsfalt, adresaAsfaltriranje);
               
        NetVision.mb.writeTwoRegister(pogon.getZadatoBrSarzi().getVrednost(), pogon.getZadatoBrSarzi().getAdresaVrednosti(), proracunKomponenti.getZadataKolicina(), 268); 
    }
    
    private void setPreddozatorePoRecepturi(db.Receptura recept) {
        pogon.getPreddozatori().getPreddozator1().setFrekfrencijaPoRecepturi(recept.getDozator1());
        pogon.getPreddozatori().getPreddozator2().setFrekfrencijaPoRecepturi(recept.getDozator2());
        pogon.getPreddozatori().getPreddozator3().setFrekfrencijaPoRecepturi(recept.getDozator3());
        pogon.getPreddozatori().getPreddozator4().setFrekfrencijaPoRecepturi(recept.getDozator4());
        pogon.getPreddozatori().getPreddozator5().setFrekfrencijaPoRecepturi(recept.getDozator5());
        pogon.getPreddozatori().getPreddozator6().setFrekfrencijaPoRecepturi(recept.getDozator6());
        pogon.getPreddozatori().getPreddozator7().setFrekfrencijaPoRecepturi(recept.getDozator7());
        pogon.getPreddozatori().getPreddozator8().setFrekfrencijaPoRecepturi(recept.getDozator8());
        pogon.getPreddozatori().getPreddozator9().setFrekfrencijaPoRecepturi(recept.getDozator9());
        pogon.getPreddozatori().getPreddozator10().setFrekfrencijaPoRecepturi(recept.getDozator10());
        pogon.getPreddozatori().getPreddozator11().setFrekfrencijaPoRecepturi(recept.getDozator11());
    }
    
    private void setParametarsPreddozatori(db.Receptura recepturaFr) {
       
        int adresaPreddozatori = 49;
        int[] podaciPreddozatori= {
            recepturaFr.getDozator1(),
            recepturaFr.getDozator2(),
            recepturaFr.getDozator3(),
            recepturaFr.getDozator4(),
            recepturaFr.getDozator5(),
            recepturaFr.getDozator6(),
            recepturaFr.getDozator7(),
            recepturaFr.getDozator8(),
            recepturaFr.getDozator9(),
            recepturaFr.getDozator10(),
            recepturaFr.getDozator11()
        };

        NetVision.mb.writeMWs(podaciPreddozatori, adresaPreddozatori);
    }
    
    
   
    
    private void saveChangeFrequency(){
        if(pogon.getPreddozatori().isSaveChangeInDb()){
            pogon.getPreddozatori().setSaveChangeInDb(false);
            
            db.Receptura recepturaFr = recepture.get(jComboBoxRecepturaFrekfrentni.getSelectedIndex());
            recepturaDb.setReceptPreddozatori(recepturaFr.getId(), 
                    pogon.getPreddozatori().getPreddozator1().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator2().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator3().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator4().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator5().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator6().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator7().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator8().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator9().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator10().getFrekfrencija().getVrednost(),
                    pogon.getPreddozatori().getPreddozator11().getFrekfrencija().getVrednost());
            
            setPreddozatorePoRecepturi(recepturaFr);
        }
        
    }

    private void prekidac(boolean uklj, int offsetUklj, boolean isklj, int offsetIsklj) {
        NetVision.mb.writePrekidac(uklj, offsetUklj, isklj, offsetIsklj);
    }

    private void taster(boolean ukljIsklj, int offset) {
        NetVision.mb.writeMX(ukljIsklj, offset);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonGorionikNaKanalu;
    private javax.swing.JToggleButton ButtonMesalica;
    private javax.swing.JToggleButton ButtonOtprasivanje;
    private javax.swing.JToggleButton ButtonPreddozator;
    private javax.swing.JToggleButton ButtonProizvodnjaAsfalta;
    private javax.swing.JToggleButton ButtonRad;
    private javax.swing.JToggleButton ButtonSusara;
    private javax.swing.JToggleButton ButtonVelikiGorionik;
    private javax.swing.JLabel MWheaderIzdatoRA;
    private javax.swing.JLabel MWheaderZadatoRA;
    private javax.swing.ButtonGroup buttonGroupIzborSilosa;
    private javax.swing.JLabel headerIzdatoAgr1;
    private javax.swing.JLabel headerIzdatoAgr2;
    private javax.swing.JLabel headerIzdatoAgr3;
    private javax.swing.JLabel headerIzdatoAgr4;
    private javax.swing.JLabel headerIzdatoAgr5;
    private javax.swing.JLabel headerIzdatoAgr6;
    private javax.swing.JLabel headerIzdatoAgr7;
    private javax.swing.JLabel headerIzdatoBit;
    private javax.swing.JLabel headerIzdatoBrSarzi;
    private javax.swing.JLabel headerIzdatoFKup;
    private javax.swing.JLabel headerIzdatoSop;
    private javax.swing.JLabel headerZadatoAgr1;
    private javax.swing.JLabel headerZadatoAgr2;
    private javax.swing.JLabel headerZadatoAgr3;
    private javax.swing.JLabel headerZadatoAgr4;
    private javax.swing.JLabel headerZadatoAgr5;
    private javax.swing.JLabel headerZadatoAgr6;
    private javax.swing.JLabel headerZadatoAgr7;
    private javax.swing.JLabel headerZadatoBit;
    private javax.swing.JLabel headerZadatoBrSarzi;
    private javax.swing.JLabel headerZadatoFKup;
    private javax.swing.JLabel headerZadatoFSop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGrejanjeVagona;
    private javax.swing.JButton jButtonPraznjenjeVagona;
    private javax.swing.JButton jButtonPromenaBrzineKorpe;
    private javax.swing.JButton jButtonPromenaSmeraKorpe;
    private javax.swing.JButton jButtonRecepturaPrihvati;
    private javax.swing.JButton jButtonRecepturaPrihvati1;
    private javax.swing.JButton jButtonSkretnica;
    private javax.swing.JButton jButtonSkretnicaIber1;
    private javax.swing.JButton jButtonSkretnicaIber2;
    private javax.swing.JButton jButtonSkretnicaVagon1;
    private javax.swing.JButton jButtonSkretnicaVagon2;
    private javax.swing.JButton jButtonStartCiklusaKorpe;
    private javax.swing.JButton jButtonStartCiklusaVagona;
    private javax.swing.JButton jButtonStartDesno;
    private javax.swing.JButton jButtonStartDizni;
    private javax.swing.JButton jButtonStartDizniKorpe;
    private javax.swing.JButton jButtonStartFrReg;
    private javax.swing.JButton jButtonStartKorpe;
    private javax.swing.JButton jButtonStartLevo;
    private javax.swing.JButton jButtonTransport;
    private javax.swing.JComboBox<String> jComboBoxRecepturaFrekfrentni;
    private javax.swing.JComboBox<String> jComboBoxRecepturaKomponente;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButtonSilos1;
    private javax.swing.JToggleButton jToggleButtonSilos2;
    private javax.swing.JToggleButton jToggleButtonSilos3;
    private javax.swing.JToggleButton jToggleButtonSilos4;
    private javax.swing.JToggleButton jToggleButtonSilos5;
    private javax.swing.JToggleButton jToggleIberVagon;
    private javax.swing.JLabel opisHeader0_2;
    private javax.swing.JLabel opisHeader16_24;
    private javax.swing.JLabel opisHeader24_32;
    private javax.swing.JLabel opisHeader2_4;
    private javax.swing.JLabel opisHeader4_8;
    private javax.swing.JLabel opisHeader8_16;
    private javax.swing.JLabel opisHeaderB1;
    private javax.swing.JLabel opisHeaderF1;
    private javax.swing.JLabel opisHeaderF2;
    private javax.swing.JLabel opisHeaderF7;
    private javax.swing.JLabel opisHeaderRA;
    private javax.swing.JLabel opisHeaderRA1;
    private javax.swing.JLabel opisHeaderRA2;
    private javax.swing.JLabel opisIzdato;
    private javax.swing.JLabel opisZadato;
    private javax.swing.JSpinner zadataKolicina;
    // End of variables declaration//GEN-END:variables
    private Timer timer;
    private final Image img;
    private Point p;

    private final Pogon pogon;
    private final RecepturaService recepturaDb;
    private final OtpremaService otpremaDb;
    private List<db.Receptura> recepture;
    private final ProracunBrSarzi proracunKomponenti;
    
    private int ciklusKorpe=0;
    private int ciklusVagona=0;
    private boolean ciklusKorpeBool=false;
    private boolean ciklusVagonaBool=false;

    //komandni prozori
    private KomandniProzorZadavanje screenZadavanjeFKup = null;
    private KomandniProzorZadavanje screenZadavanjeFSop = null;
    private KomandniProzorZadavanje screenZadavanje0_32 = null;
    private KomandniProzorZadavanje screenZadavanje0_4 = null;
    private KomandniProzorZadavanje screenZadavanje4_8 = null;
    private KomandniProzorZadavanje screenZadavanje8_11 = null;
    private KomandniProzorZadavanje screenZadavanje11_16 = null;
    private KomandniProzorZadavanje screenZadavanje16_22 = null;
    private KomandniProzorZadavanje screenZadavanje16_32 = null;
    private KomandniProzorZadavanje screenZadavanjeBitumen = null;
}
