/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozoriOld;

import dbService.GradilisteService;
import dbService.KupciService;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author branko.scekic
 */
public class KupacFrame extends javax.swing.JFrame {

    /**
     * Creates new form KupacFrame
     *
     * @param kupacDb
     * @param gradilisteDb
     */
    public KupacFrame(KupciService kupacDb, GradilisteService gradilisteDb) {
        initComponents();

        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        this.kupacDb = kupacDb;
        this.gradilisteDb = gradilisteDb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNoviKupacOdustani = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableGradiliste = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        kupacMatBr = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        kupacUlicaIBr = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        kupacPIB = new javax.swing.JTextField();
        jButtonNoviKupacPotvrdi = new javax.swing.JButton();
        jLabel111 = new javax.swing.JLabel();
        kupacSifarnik = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        kupacPostanskiBr = new javax.swing.JTextField();
        kupacMesto = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        kupacDrzava = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        kupacIme1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jLabelKupac = new javax.swing.JLabel();
        gradilisteType = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButtonNovoGradilistePotvrdi = new javax.swing.JButton();
        kupacImeFilter = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKupac1 = new javax.swing.JTable();

        setResizable(false);

        jButtonNoviKupacOdustani.setText("Odustani");
        jButtonNoviKupacOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviKupacOdustaniActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Obrisi kupca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableGradiliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "br", "Gradiliste"
            }
        ));
        jTableGradiliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGradilisteMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableGradiliste);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel109.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel109.setText("MB");

        jLabel107.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel107.setText("ulica i br");

        jLabel108.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel108.setText("PIB");

        jButtonNoviKupacPotvrdi.setBackground(new java.awt.Color(0, 255, 255));
        jButtonNoviKupacPotvrdi.setText("Sacuvaj kupca");
        jButtonNoviKupacPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviKupacPotvrdiActionPerformed(evt);
            }
        });

        jLabel111.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel111.setText("Sifarnik:");

        jLabel112.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel112.setText("Postanski br");

        jLabel113.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel113.setText("Mesto");

        jLabel114.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel114.setText("Drzava");

        jLabel115.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel115.setText("Naziv kupaca ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel108, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kupacPIB, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(kupacMesto)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kupacUlicaIBr))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNoviKupacPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kupacDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kupacPostanskiBr, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kupacMatBr, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kupacSifarnik, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel115)
                        .addGap(18, 18, 18)
                        .addComponent(kupacIme1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kupacSifarnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kupacIme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupacMatBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupacPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupacPostanskiBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupacMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupacUlicaIBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonNoviKupacPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kupacDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel105.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel105.setText("Selektovan kupac:");

        jLabelKupac.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKupac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelKupac.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKupac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKupac)
                    .addComponent(jLabel105))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel110.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel110.setText("Dodaj gradiliste");

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Obrisi gradiliste");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonNovoGradilistePotvrdi.setBackground(new java.awt.Color(0, 255, 255));
        jButtonNovoGradilistePotvrdi.setText("Dodaj gradiliste");
        jButtonNovoGradilistePotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoGradilistePotvrdiActionPerformed(evt);
            }
        });

        kupacImeFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kupacImeFilterMouseEntered(evt);
            }
        });

        jLabel106.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel106.setText("Filtriraj naziv kupca: ");

        jTableKupac1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKupac1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableKupac1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKupac1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kupacImeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel110, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(gradilisteType, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovoGradilistePotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNoviKupacOdustani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradilisteType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kupacImeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNovoGradilistePotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonNoviKupacOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoviKupacPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviKupacPotvrdiActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            try {
                kupacDb.updateKupac(kupacSifarnik.getText(), kupacMatBr.getText(), kupacPostanskiBr.getText(),
                        kupacDrzava.getText(), kupacMesto.getText(), kupacPIB.getText(), kupacIme1.getText(), kupacUlicaIBr.getText());

                kupacSifarnik.setText("");
                kupacMatBr.setText("");
                kupacPostanskiBr.setText("");
                kupacDrzava.setText("");
                kupacMesto.setText("");
                kupacPIB.setText("");
                kupacIme1.setText("");
                kupacUlicaIBr.setText("");

            } catch (Exception e) {
                try {
                    kupacDb.addKupac(kupacSifarnik.getText(), kupacMatBr.getText(), kupacPostanskiBr.getText(),
                            kupacDrzava.getText(), kupacMesto.getText(), kupacPIB.getText(), kupacIme1.getText(), kupacUlicaIBr.getText());

                    kupacSifarnik.setText("");
                    kupacMatBr.setText("");
                    kupacPostanskiBr.setText("");
                    kupacDrzava.setText("");
                    kupacMesto.setText("");
                    kupacPIB.setText("");
                    kupacIme1.setText("");
                    kupacUlicaIBr.setText("");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Nije uspela promena ili dodavanje kupca");
                }
            }

            getKupci();
        }
    }//GEN-LAST:event_jButtonNoviKupacPotvrdiActionPerformed

    private void jButtonNoviKupacOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviKupacOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNoviKupacOdustaniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = jTableKupac1.getModel().getValueAt(jTableKupac1.getSelectedRow(), 6).toString();
        if (JOptionPane.showConfirmDialog(null, "Da li želite da obrisete " + "kupac" + "?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            kupacDb.deleteKupac(id);
            getKupci();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void writeDataOnTextBox() {
        kupacDrzava.setText(kupac.getNazivdrzave());
        kupacIme1.setText(kupac.getSkraceninazivpartnera());
        kupacMatBr.setText(kupac.getMaticnibrojsudskogregistra());
        kupacMesto.setText(kupac.getNazivmesta());
        kupacPIB.setText(kupac.getPoreskiidentifikacionibroj());
        kupacPostanskiBr.setText(kupac.getMesto());
        kupacSifarnik.setText(kupac.getSifrapartnera());
        kupacUlicaIBr.setText(kupac.getUlicaibroj());
    }

    private void jTableGradilisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGradilisteMouseClicked

    }//GEN-LAST:event_jTableGradilisteMouseClicked

    private void jButtonNovoGradilistePotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoGradilistePotvrdiActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gradilisteDb.addGradiliste(gradilisteType.getText(), kupac);
            getGradiliste(kupac);
        }
    }//GEN-LAST:event_jButtonNovoGradilistePotvrdiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        long id = Long.parseLong(jTableGradiliste.getModel().getValueAt(jTableGradiliste.getSelectedRow(), 2).toString());
        if (JOptionPane.showConfirmDialog(null, "Da li želite da obrisete gradiliste ?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            gradilisteDb.deleteGradiliste(id);
            getGradiliste(kupac);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTableKupac1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKupac1MousePressed
        String id = jTableKupac1.getModel().getValueAt(jTableKupac1.getSelectedRow(), 6).toString();
        kupac = kupacDb.getKupacSifarnik(id);
        writeDataOnTextBox();
        getGradiliste(kupac);
    }//GEN-LAST:event_jTableKupac1MousePressed

    private void kupacImeFilterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kupacImeFilterMouseEntered
        updateResult(kupacDb.getKupci());
    }//GEN-LAST:event_kupacImeFilterMouseEntered

    public void getKupci() {
        updateResult(kupacDb.getKupci());
    }

    private void updateResult(List<dbOld.Kupci> result) {
        int i = 0;
        int size = 0;

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAktivan()) {
                size++;
            }
        }

        Object[][] obj = new Object[size][7];

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAktivan()) {
                obj[i][0] = i + 1;
                obj[i][1] = result.get(j).getSkraceninazivpartnera();
                obj[i][2] = result.get(j).getMaticnibrojsudskogregistra();
                obj[i][3] = result.get(j).getPoreskiidentifikacionibroj();
                obj[i][4] = result.get(j).getNazivmesta();
                obj[i][5] = result.get(j).getUlicaibroj();
                obj[i][6] = result.get(j).getSifrapartnera();
                i++;
            }
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Kupac", "MB", "PIB", "Mesto", "Adresa", "id"});
        jTableKupac1.setModel(model);
        jTableKupac1.setRowMargin(4);
        jTableKupac1.setRowHeight(40);
        jTableKupac1.getColumnModel().getColumn(0).setMaxWidth(45);

        rowSorter = new TableRowSorter<>(jTableKupac1.getModel());
        jTableKupac1.removeColumn(jTableKupac1.getColumnModel().getColumn(6));

        jTableKupac1.setRowSorter(rowSorter);
        addFilter();
    }

    private void addFilter() {
        kupacImeFilter.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = kupacImeFilter.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = kupacImeFilter.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                System.out.println(e);
            }

        });
    }

    /*
    private void addFilterGradiliste() {
        gradilisteType.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = gradilisteType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = gradilisteType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
*/
    public void getGradiliste(dbOld.Kupci kupac) {
        updateResultGradiliste(gradilisteDb.getGradiliste(kupac));
    }

    private void updateResultGradiliste(List<dbOld.Gradiliste> result) {
        int i = 0;
        int size = 0;

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAktivno()) {
                size++;
            }
        }

        Object[][] obj = new Object[size][3];

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAktivno()) {
                obj[i][0] = i + 1;
                obj[i][1] = result.get(j).getGradiliste();
                obj[i][2] = result.get(j).getId();
                i++;
            }
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Gradiliste", "id"});
        jTableGradiliste.setModel(model);
        jTableGradiliste.setRowMargin(4);
        jTableGradiliste.setRowHeight(40);
        jTableGradiliste.getColumnModel().getColumn(0).setMaxWidth(45);

        this.rowSorter = new TableRowSorter<>(jTableGradiliste.getModel());
        jTableGradiliste.removeColumn(jTableGradiliste.getColumnModel().getColumn(2));

        jTableGradiliste.setRowSorter(rowSorter);
        //addFilterGradiliste();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gradilisteType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonNoviKupacOdustani;
    private javax.swing.JButton jButtonNoviKupacPotvrdi;
    private javax.swing.JButton jButtonNovoGradilistePotvrdi;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabelKupac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableGradiliste;
    private javax.swing.JTable jTableKupac1;
    private javax.swing.JTextField kupacDrzava;
    private javax.swing.JTextField kupacIme1;
    private javax.swing.JTextField kupacImeFilter;
    private javax.swing.JTextField kupacMatBr;
    private javax.swing.JTextField kupacMesto;
    private javax.swing.JTextField kupacPIB;
    private javax.swing.JTextField kupacPostanskiBr;
    private javax.swing.JTextField kupacSifarnik;
    private javax.swing.JTextField kupacUlicaIBr;
    // End of variables declaration//GEN-END:variables

    public final KupciService kupacDb;
    public final GradilisteService gradilisteDb;
    private TableRowSorter rowSorter;
    private dbOld.Kupci kupac;
}
