/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozoriOld;

import com.Buff;
import dbService.SilosiService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.Timer;
import pogon.Pogon;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class StanjeZalihaFrame extends javax.swing.JFrame {

    /**
     * Creates new form StanjeZalihaFrame
     * @param silosiDb
     * @param pogon
     */
    public StanjeZalihaFrame(SilosiService silosiDb, Pogon pogon) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.silosiDb = silosiDb;
        this.pogon = pogon;
        
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButtonStanjeZalihaOdustani = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButtonDodajStannjeZaliha = new javax.swing.JButton();
        StanjeZalihaFrakcija04 = new javax.swing.JLabel();
        StanjeZalihaFrakcija48 = new javax.swing.JLabel();
        StanjeZalihaFrakcija816 = new javax.swing.JLabel();
        StanjeZalihaAditiv3 = new javax.swing.JLabel();
        StanjeZalihaCement = new javax.swing.JLabel();
        StanjeZalihaFiler = new javax.swing.JLabel();
        StanjeZalihaAditiv1 = new javax.swing.JLabel();
        StanjeZalihaAditiv2 = new javax.swing.JLabel();
        DodajZaliheFrakcija04 = new javax.swing.JSpinner();
        DodajZaliheFrakcija48 = new javax.swing.JSpinner();
        DodajZaliheFrakcija816 = new javax.swing.JSpinner();
        DodajZaliheAditiv3 = new javax.swing.JSpinner();
        DodajZaliheCement = new javax.swing.JSpinner();
        DodajZaliheFiler = new javax.swing.JSpinner();
        DodajZaliheAditiv1 = new javax.swing.JSpinner();
        DodajZaliheAditiv2 = new javax.swing.JSpinner();
        jButtonNulirajSilos1 = new javax.swing.JButton();
        jButtonNulirajSilos2 = new javax.swing.JButton();

        setResizable(false);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Stanje zaliha");
        jLabel32.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        jButtonStanjeZalihaOdustani.setText("Odustani");
        jButtonStanjeZalihaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStanjeZalihaOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonStanjeZalihaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonStanjeZalihaOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("1. Frakcija 0-4 mm");
        jLabel35.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("2. Frakcija 4-8 mm");
        jLabel39.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("3. Frakcija 8-16 mm");
        jLabel40.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("8. Aditiv A3");
        jLabel41.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("4. Cement sil 1");
        jLabel42.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("5. Cement sil 2");
        jLabel43.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("6. Aditiv A1");
        jLabel44.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("7. Aditiv A2");
        jLabel45.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jButtonDodajStannjeZaliha.setText("Dodaj");
        jButtonDodajStannjeZaliha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStannjeZalihaActionPerformed(evt);
            }
        });

        StanjeZalihaFrakcija04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaFrakcija04.setText("0");
        StanjeZalihaFrakcija04.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaFrakcija48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaFrakcija48.setText("0");
        StanjeZalihaFrakcija48.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaFrakcija816.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaFrakcija816.setText("0");
        StanjeZalihaFrakcija816.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaAditiv3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaAditiv3.setText("0");
        StanjeZalihaAditiv3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaCement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaCement.setText("0");
        StanjeZalihaCement.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaFiler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaFiler.setText("0");
        StanjeZalihaFiler.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaAditiv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaAditiv1.setText("0");
        StanjeZalihaAditiv1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        StanjeZalihaAditiv2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StanjeZalihaAditiv2.setText("0");
        StanjeZalihaAditiv2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        DodajZaliheFrakcija04.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-1000000.0f), Float.valueOf(1000000.0f), Float.valueOf(1.0f)));

        DodajZaliheFrakcija48.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-1000000.0f), Float.valueOf(1000000.0f), Float.valueOf(1.0f)));

        DodajZaliheFrakcija816.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-1000000.0f), Float.valueOf(1000000.0f), Float.valueOf(1.0f)));

        DodajZaliheAditiv3.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-100000.0f), Float.valueOf(100000.0f), Float.valueOf(1.0f)));

        DodajZaliheCement.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-1000000.0f), Float.valueOf(1000000.0f), Float.valueOf(1.0f)));

        DodajZaliheFiler.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-1000000.0f), Float.valueOf(1000000.0f), Float.valueOf(1.0f)));

        DodajZaliheAditiv1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-100000.0f), Float.valueOf(100000.0f), Float.valueOf(1.0f)));

        DodajZaliheAditiv2.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-100000.0f), Float.valueOf(100000.0f), Float.valueOf(1.0f)));

        jButtonNulirajSilos1.setText("Nuliraj silos 1");
        jButtonNulirajSilos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNulirajSilos1ActionPerformed(evt);
            }
        });

        jButtonNulirajSilos2.setText("Nuliraj silos 2");
        jButtonNulirajSilos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNulirajSilos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButtonDodajStannjeZaliha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaFrakcija04, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaFrakcija48, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaFrakcija816, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaAditiv3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaCement, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaFiler, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaAditiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StanjeZalihaAditiv2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DodajZaliheFrakcija04, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheFrakcija48, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheFrakcija816, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheAditiv3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheCement, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheFiler, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheAditiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DodajZaliheAditiv2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNulirajSilos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNulirajSilos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaFrakcija04)
                    .addComponent(DodajZaliheFrakcija04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaFrakcija48)
                    .addComponent(DodajZaliheFrakcija48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaFrakcija816)
                    .addComponent(DodajZaliheFrakcija816, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaCement)
                    .addComponent(DodajZaliheCement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNulirajSilos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaFiler)
                    .addComponent(DodajZaliheFiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNulirajSilos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaAditiv1)
                    .addComponent(DodajZaliheAditiv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaAditiv2)
                    .addComponent(DodajZaliheAditiv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StanjeZalihaAditiv3)
                    .addComponent(DodajZaliheAditiv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDodajStannjeZaliha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStanjeZalihaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStanjeZalihaOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonStanjeZalihaOdustaniActionPerformed

    private void jButtonDodajStannjeZalihaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStannjeZalihaActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //addStanjeZaliha();
        }
    }//GEN-LAST:event_jButtonDodajStannjeZalihaActionPerformed

    private void jButtonNulirajSilos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNulirajSilos1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da nulirate silos br 1?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            nulirajStanje(1,"Silos cementa br 1");
           // pogon.getCement().setProcenjenaKolicinaSilos1(0);
        
        }
    }//GEN-LAST:event_jButtonNulirajSilos1ActionPerformed

    private void jButtonNulirajSilos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNulirajSilos2ActionPerformed
         if (JOptionPane.showConfirmDialog(null, "Da li želite da nulirate silos br 2?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            nulirajStanje(2,"Silos cementa br 2");
           // pogon.getCement().setProcenjenaKolicinaSilos2(0);
        }
    }//GEN-LAST:event_jButtonNulirajSilos2ActionPerformed

    public JSpinner getDodajZaliheAditiv1() {
        return DodajZaliheAditiv1;
    }

    public JSpinner getDodajZaliheAditiv2() {
        return DodajZaliheAditiv2;
    }

    public JSpinner getDodajZaliheCement() {
        return DodajZaliheCement;
    }

    public JSpinner getDodajZaliheFiler() {
        return DodajZaliheFiler;
    }

    public JSpinner getDodajZaliheFrakcija04() {
        return DodajZaliheFrakcija04;
    }

    public JSpinner getDodajZaliheAditiv3() {
        return DodajZaliheAditiv3;
    }

    public JSpinner getDodajZaliheFrakcija48() {
        return DodajZaliheFrakcija48;
    }

    public JSpinner getDodajZaliheFrakcija816() {
        return DodajZaliheFrakcija816;
    }

    public JLabel getStanjeZalihaAditiv1() {
        return StanjeZalihaAditiv1;
    }

    public JLabel getStanjeZalihaAditiv2() {
        return StanjeZalihaAditiv2;
    }

    public JLabel getStanjeZalihaCement() {
        return StanjeZalihaCement;
    }

    public JLabel getStanjeZalihaFiler() {
        return StanjeZalihaFiler;
    }

    public JLabel getStanjeZalihaFrakcija04() {
        return StanjeZalihaFrakcija04;
    }

    public JLabel getStanjeZalihaFrakcija1632() {
        return StanjeZalihaAditiv3;
    }

    public JLabel getStanjeZalihaFrakcija48() {
        return StanjeZalihaFrakcija48;
    }

    public JLabel getStanjeZalihaFrakcija816() {
        return StanjeZalihaFrakcija816;
    }
    
    public void setMb(Buff mb){
        this.mb = mb;
    }
    
    
    public void getStanjeZaliha(){
       
       // StanjeZalihaCement.setText(Convert.shiftPointUnsign(pogon.getCement().getProcenjenaKolicinaSilos1(), pogon.getCement().getBrDec()));
       // StanjeZalihaFiler.setText(Convert.shiftPointUnsign( pogon.getCement().getProcenjenaKolicinaSilos2(), pogon.getCement().getBrDec()));
        /*
        StanjeZalihaAditiv1.setText(Convert.shiftPointUnsign(pogon.getAditiv1().getProcenjenaKolicinaSilos(), pogon.getAditiv1().getBrDec()));
        StanjeZalihaAditiv2.setText(Convert.shiftPointUnsign(pogon.getAditiv2().getProcenjenaKolicinaSilos(), pogon.getAditiv2().getBrDec()));
        StanjeZalihaAditiv3.setText(Convert.shiftPointUnsign(pogon.getAditiv3().getProcenjenaKolicinaSilos(), pogon.getAditiv3().getBrDec()));
        StanjeZalihaFrakcija04.setText(Convert.shiftPointUnsign(pogon.getAgregat0_4().getProcenjenaKolicinaSilos(), pogon.getAgregat0_4().getBrDec()));
        StanjeZalihaFrakcija48.setText(Convert.shiftPointUnsign(pogon.getAgregat4_8().getProcenjenaKolicinaSilos(), pogon.getAgregat4_8().getBrDec()));
        StanjeZalihaFrakcija816.setText(Convert.shiftPointUnsign(pogon.getAgregat8_16().getProcenjenaKolicinaSilos(), pogon.getAgregat8_16().getBrDec()));
        /*
    }
    
    
    public void addStanjeZaliha(){
       /*
        double cem = Convert.shiftPointDoubleUnsign(pogon.getCement().getProcenjenaKolicinaSilos1(), pogon.getCement().getBrDec());
        double fil = Convert.shiftPointDoubleUnsign(pogon.getCement().getProcenjenaKolicinaSilos2(), pogon.getCement().getBrDec());
        double agr04 = Convert.shiftPointDoubleUnsign(pogon.getAgregat0_4().getProcenjenaKolicinaSilos(), pogon.getAgregat0_4().getBrDec());
        double agr48 = Convert.shiftPointDoubleUnsign(pogon.getAgregat4_8().getProcenjenaKolicinaSilos(), pogon.getAgregat4_8().getBrDec());
        double agr816 = Convert.shiftPointDoubleUnsign(pogon.getAgregat8_16().getProcenjenaKolicinaSilos(), pogon.getAgregat8_16().getBrDec());
        double ad1 = Convert.shiftPointDoubleUnsign(pogon.getAditiv1().getProcenjenaKolicinaSilos(), 0);
        double ad2 = Convert.shiftPointDoubleUnsign(pogon.getAditiv2().getProcenjenaKolicinaSilos(), 0);
        double ad3 = Convert.shiftPointDoubleUnsign(pogon.getAditiv3().getProcenjenaKolicinaSilos(), 0);
        */
        
        if(Convert.stringToDouble(DodajZaliheCement.getValue().toString(),0)!=0){
           // silosiDb.setKolicina(1, cem + Convert.stringToDouble(DodajZaliheCement.getValue().toString(),0)
           //         , Convert.stringToDouble(DodajZaliheCement.getValue().toString(),0), "Silos cementa br 1");
        }
        if(Convert.stringToDouble(DodajZaliheFiler.getValue().toString(),0)!=0){
            //silosiDb.setKolicina(2, fil +  Convert.stringToDouble(DodajZaliheFiler.getValue().toString(),0)
            //        , Convert.stringToDouble(DodajZaliheFiler.getValue().toString(),0), "Silos cementa br 2");
        }
        if(Convert.stringToDouble(DodajZaliheFrakcija04.getValue().toString(),0)!=0){
            //silosiDb.setKolicina(3, agr04 + Convert.stringToDouble(DodajZaliheFrakcija04.getValue().toString(),0)
            //        , Convert.stringToDouble(DodajZaliheFrakcija04.getValue().toString(),0), "Silos agregat 0-4");
        }
        if(Convert.stringToDouble(DodajZaliheFrakcija48.getValue().toString(),0)!=0){
            //silosiDb.setKolicina(4, agr48 + Convert.stringToDouble(DodajZaliheFrakcija48.getValue().toString(),0)
            //        , Convert.stringToDouble(DodajZaliheFrakcija48.getValue().toString(),0), "Silos agregat 4-8");
        }
        if(Convert.stringToDouble(DodajZaliheFrakcija816.getValue().toString(),0)!=0){
            //silosiDb.setKolicina(5, agr816 + Convert.stringToDouble(DodajZaliheFrakcija816.getValue().toString(),0)
            //        , Convert.stringToDouble(DodajZaliheFrakcija816.getValue().toString(),0), "Silos agregat 8-16");
        }
        if(Convert.stringToDouble(DodajZaliheAditiv1.getValue().toString(),2)!=0){
            //silosiDb.setKolicina(6, ad1 + Convert.stringToDouble(DodajZaliheAditiv1.getValue().toString(),2)
            //        , Convert.stringToDouble(DodajZaliheAditiv1.getValue().toString(),2), "Silos aditiv1");
        }
        if(Convert.stringToDouble(DodajZaliheAditiv2.getValue().toString(),2)!=0){
            //silosiDb.setKolicina(7, ad1 + Convert.stringToDouble(DodajZaliheAditiv2.getValue().toString(),2)
            //        , Convert.stringToDouble(DodajZaliheAditiv2.getValue().toString(),2), "Silos aditiv2");
        }
         if(Convert.stringToDouble(DodajZaliheAditiv3.getValue().toString(),2)!=0){
           // silosiDb.setKolicina(8, ad1 + Convert.stringToDouble(DodajZaliheAditiv3.getValue().toString(),2)
           //         , Convert.stringToDouble(DodajZaliheAditiv3.getValue().toString(),2), "Silos aditiv3");
        }
        
       /*         
        int cement = Convert.convertLongInInt_in1PlusIn2(cem ,DodajZaliheCement.getValue().toString() ,0);
        int filer = Convert.convertLongInInt_in1PlusIn2(fil, DodajZaliheFiler.getValue().toString() , 0);
        int agregat04 = Convert.convertLongInInt_in1PlusIn2(agr04, DodajZaliheFrakcija04.getValue().toString(), 0);
        int agregat48 = Convert.convertLongInInt_in1PlusIn2(agr48, DodajZaliheFrakcija48.getValue().toString(),0);
        int agregat816 = Convert.convertLongInInt_in1PlusIn2(agr816, DodajZaliheFrakcija816.getValue().toString(), 0);
      
        
        int aditiv1 = Convert.convertLongInInt_in1PlusIn2(ad1, DodajZaliheAditiv1.getValue().toString(),2);
        int aditiv2 = Convert.convertLongInInt_in1PlusIn2(ad2, DodajZaliheAditiv2.getValue().toString(),2);
        int aditiv3 = Convert.convertLongInInt_in1PlusIn2(ad3, DodajZaliheAditiv3.getValue().toString(),2);
        /*
        pogon.getCement().setProcenjenaKolicinaSilos1(cement);
        pogon.getCement().setProcenjenaKolicinaSilos2(filer);
        pogon.getAgregat0_4().setProcenjenaKolicinaSilos(agregat04);
        pogon.getAgregat4_8().setProcenjenaKolicinaSilos(agregat48);
       
        pogon.getAgregat8_16().setProcenjenaKolicinaSilos(agregat816);
        pogon.getAditiv3().setProcenjenaKolicinaSilos(aditiv3);
        pogon.getAditiv1().setProcenjenaKolicinaSilos(aditiv1);
        pogon.getAditiv2().setProcenjenaKolicinaSilos(aditiv2);
        */
        resetSpinner();
    }
    
    
    private void nulirajStanje(int brSilosa, String opis){
        silosiDb.nuliraj(brSilosa, opis);
    }
    
    
    private void resetSpinner(){
        DodajZaliheCement.setValue(0);
        DodajZaliheFiler.setValue(0);
        DodajZaliheFrakcija04.setValue(0);
        DodajZaliheFrakcija48.setValue(0);
        DodajZaliheFrakcija816.setValue(0);
        DodajZaliheAditiv3.setValue(0);
        DodajZaliheAditiv1.setValue(0);
        DodajZaliheAditiv2.setValue(0);
    }
    
    private void refresh() {
        timer = new Timer(1000, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                getStanjeZaliha();
            }

        });
        timer.start();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner DodajZaliheAditiv1;
    private javax.swing.JSpinner DodajZaliheAditiv2;
    private javax.swing.JSpinner DodajZaliheAditiv3;
    private javax.swing.JSpinner DodajZaliheCement;
    private javax.swing.JSpinner DodajZaliheFiler;
    private javax.swing.JSpinner DodajZaliheFrakcija04;
    private javax.swing.JSpinner DodajZaliheFrakcija48;
    private javax.swing.JSpinner DodajZaliheFrakcija816;
    private javax.swing.JLabel StanjeZalihaAditiv1;
    private javax.swing.JLabel StanjeZalihaAditiv2;
    private javax.swing.JLabel StanjeZalihaAditiv3;
    private javax.swing.JLabel StanjeZalihaCement;
    private javax.swing.JLabel StanjeZalihaFiler;
    private javax.swing.JLabel StanjeZalihaFrakcija04;
    private javax.swing.JLabel StanjeZalihaFrakcija48;
    private javax.swing.JLabel StanjeZalihaFrakcija816;
    private javax.swing.JButton jButtonDodajStannjeZaliha;
    private javax.swing.JButton jButtonNulirajSilos1;
    private javax.swing.JButton jButtonNulirajSilos2;
    private javax.swing.JButton jButtonStanjeZalihaOdustani;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    // End of variables declaration//GEN-END:variables
    public final SilosiService silosiDb;
    private Buff mb;
    private final Pogon pogon;
    private Timer timer;
}
