/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozoriOld;

/**
 *
 * @author Branko
 */
public class TekuciRNiOtprema extends javax.swing.JFrame {

    /**
     * Creates new form TekuciRNiOtprema
     */
    public TekuciRNiOtprema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOtkaziRN = new javax.swing.JButton();
        shorcutAktivniRadniNaloti = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tekuciBrojRN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tekucaMarkaBetona = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tekuciKupac = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tekuceGradiliste = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tekuceUgovoreno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tekuceIsporuceno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tekucePreostalo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonOtkaziOtpremu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tekuceTablicaVozila = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tekuceVozac = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        zadatoBetonam3 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        tekuceTrenutno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonNovaOtprema = new javax.swing.JButton();
        jButtonStartCiklus = new javax.swing.JButton();
        jButtonStopCiklusa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Tekući radni nalog");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(140, 20, 150, 23);

        jButtonOtkaziRN.setText("Otkaži Radni nalog");
        jButtonOtkaziRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziRNActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOtkaziRN);
        jButtonOtkaziRN.setBounds(20, 50, 140, 40);

        shorcutAktivniRadniNaloti.setText("Aktivni R.N.");
        shorcutAktivniRadniNaloti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shorcutAktivniRadniNalotiActionPerformed(evt);
            }
        });
        jPanel3.add(shorcutAktivniRadniNaloti);
        shorcutAktivniRadniNaloti.setBounds(230, 50, 120, 40);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Broj RN :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 100, 70, 17);

        tekuciBrojRN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tekuciBrojRN.setText("RN");
        jPanel3.add(tekuciBrojRN);
        tekuciBrojRN.setBounds(120, 100, 130, 22);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Marka betona:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 140, 88, 17);

        tekucaMarkaBetona.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tekucaMarkaBetona.setText("MB");
        jPanel3.add(tekucaMarkaBetona);
        tekucaMarkaBetona.setBounds(120, 140, 250, 22);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Kupac:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 180, 41, 17);

        tekuciKupac.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tekuciKupac.setText("K");
        jPanel3.add(tekuciKupac);
        tekuciKupac.setBounds(120, 180, 250, 22);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Gradilište:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 220, 60, 17);

        tekuceGradiliste.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tekuceGradiliste.setText("G");
        jPanel3.add(tekuceGradiliste);
        tekuceGradiliste.setBounds(120, 220, 250, 24);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Ugovoreno po RN :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 270, 113, 17);

        tekuceUgovoreno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tekuceUgovoreno.setText("M3");
        jPanel3.add(tekuceUgovoreno);
        tekuceUgovoreno.setBounds(240, 270, 90, 17);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Isporučeno po RN :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 310, 114, 17);

        tekuceIsporuceno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tekuceIsporuceno.setText("M3");
        jPanel3.add(tekuceIsporuceno);
        tekuceIsporuceno.setBounds(240, 310, 100, 17);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Preostalo za isporuku po RN :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 350, 174, 17);

        tekucePreostalo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tekucePreostalo.setText("M3");
        jPanel3.add(tekucePreostalo);
        tekucePreostalo.setBounds(240, 350, 90, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 380, 390);

        jButtonOtkaziOtpremu.setText("Zavrsi zapoceto");
        jButtonOtkaziOtpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziOtpremuActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOtkaziOtpremu);
        jButtonOtkaziOtpremu.setBounds(20, 420, 113, 40);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Tekuća otprema");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 420, 123, 23);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Broj vozila:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(70, 490, 66, 17);

        tekuceTablicaVozila.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tekuceTablicaVozila.setText("T");
        jPanel3.add(tekuceTablicaVozila);
        tekuceTablicaVozila.setBounds(190, 480, 140, 24);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Vozač:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(100, 530, 39, 17);

        tekuceVozac.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tekuceVozac.setText("V");
        jPanel3.add(tekuceVozac);
        tekuceVozac.setBounds(190, 520, 120, 24);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Zadato:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(90, 570, 46, 17);

        zadatoBetonam3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        zadatoBetonam3.setText("0");
        jPanel3.add(zadatoBetonam3);
        zadatoBetonam3.setBounds(190, 560, 70, 24);

        jLabel120.setText("m3");
        jPanel3.add(jLabel120);
        jLabel120.setBounds(260, 570, 20, 16);

        jLabel121.setText("m3");
        jPanel3.add(jLabel121);
        jLabel121.setBounds(260, 610, 30, 16);

        tekuceTrenutno.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        tekuceTrenutno.setText("0");
        jPanel3.add(tekuceTrenutno);
        tekuceTrenutno.setBounds(190, 600, 60, 24);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Trenutno:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(80, 610, 60, 17);

        jButtonNovaOtprema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/new order.png"))); // NOI18N
        jButtonNovaOtprema.setText("          Nova otprema");
        jButtonNovaOtprema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaOtpremaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNovaOtprema);
        jButtonNovaOtprema.setBounds(70, 670, 260, 70);

        jButtonStartCiklus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/Play_48x48.png"))); // NOI18N
        jButtonStartCiklus.setText("Start ciklusa");
        jButtonStartCiklus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartCiklusActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonStartCiklus);
        jButtonStartCiklus.setBounds(0, 750, 160, 60);

        jButtonStopCiklusa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/Stop_48x48.png"))); // NOI18N
        jButtonStopCiklusa.setText("Zaustavi ciklus");
        jButtonStopCiklusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopCiklusaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonStopCiklusa);
        jButtonStopCiklusa.setBounds(210, 750, 170, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dodatak main screen.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 390, 380, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOtkaziRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziRNActionPerformed
        //if (JOptionPane.showConfirmDialog(null, "Da li želite da otkazete radni nalog?", "Upozorenje",
            //    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        //radniNalogDb.setRnStatus(2, radniNalogDb.getRN(tekuciRN.getTekuciRN().getRn()));
        //}
    }//GEN-LAST:event_jButtonOtkaziRNActionPerformed

    private void shorcutAktivniRadniNalotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shorcutAktivniRadniNalotiActionPerformed
        //aktivniRadniNaloziFrame.setVisible(true);
        //aktivniRadniNaloziFrame.getAktivniRN();
    }//GEN-LAST:event_shorcutAktivniRadniNalotiActionPerformed

    private void jButtonOtkaziOtpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziOtpremuActionPerformed
        //mb.writeMX(true, pogon.getOstalo().getZavrsiCiklus().getKomandaAdresa());
        //otpremaDb.promeniStatus(StatusOtprema.getStorniran(), tekuciRN.getTekucaOtp().getId());
    }//GEN-LAST:event_jButtonOtkaziOtpremuActionPerformed

    private void jButtonNovaOtpremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaOtpremaActionPerformed
        //getNewOtpremaFromRN();
    }//GEN-LAST:event_jButtonNovaOtpremaActionPerformed

    private void jButtonStartCiklusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartCiklusActionPerformed
        //mb.writeMX(true, pogon.getOstalo().getStartCiklus().getKomandaAdresa());
    }//GEN-LAST:event_jButtonStartCiklusActionPerformed

    private void jButtonStopCiklusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopCiklusaActionPerformed
        //mb.writeMX(true, pogon.getOstalo().getStopCiklus().getKomandaAdresa());
        //otpremaDb.promeniStatus(StatusOtprema.getStorniran(), tekuciRN.getTekucaOtp().getId());
    }//GEN-LAST:event_jButtonStopCiklusaActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNovaOtprema;
    private javax.swing.JButton jButtonOtkaziOtpremu;
    private javax.swing.JButton jButtonOtkaziRN;
    private javax.swing.JButton jButtonStartCiklus;
    private javax.swing.JButton jButtonStopCiklusa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton shorcutAktivniRadniNaloti;
    private javax.swing.JLabel tekucaMarkaBetona;
    private javax.swing.JLabel tekuceGradiliste;
    private javax.swing.JLabel tekuceIsporuceno;
    private javax.swing.JLabel tekucePreostalo;
    private javax.swing.JLabel tekuceTablicaVozila;
    private javax.swing.JLabel tekuceTrenutno;
    private javax.swing.JLabel tekuceUgovoreno;
    private javax.swing.JLabel tekuceVozac;
    private javax.swing.JLabel tekuciBrojRN;
    private javax.swing.JLabel tekuciKupac;
    private javax.swing.JLabel zadatoBetonam3;
    // End of variables declaration//GEN-END:variables
}
