/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozoriOld;

import dbService.VozacService;
import dbService.VoziloService;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author branko.scekic
 */
public class VozacFrame extends javax.swing.JFrame {

    /**
     * Creates new form VozacFrame
     * @param vozacDb
     */
    public VozacFrame(VozacService vozacDb, VoziloService voziloDb) {
        initComponents();
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        this.vozacDb = vozacDb;
        this.voziloDb = voziloDb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableVozaci = new javax.swing.JTable();
        jButtonNoviVozacOdustani = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        vozacType = new javax.swing.JTextField();
        jButtonNoviVozacPotvrdi = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableVozila = new javax.swing.JTable();
        jLabelVozac = new javax.swing.JLabel();
        voziloType = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        jButtonNovoVoziloPotvrdi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        garazaType = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();

        setResizable(false);

        jLabel108.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("Selektovan vozac:");

        jTableVozaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "br", "Vozac"
            }
        ));
        jTableVozaci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVozaciMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableVozaci);

        jButtonNoviVozacOdustani.setText("Odustani");
        jButtonNoviVozacOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviVozacOdustaniActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Obrisi vozaca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel109.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel109.setText("Vozač");

        jButtonNoviVozacPotvrdi.setBackground(new java.awt.Color(51, 255, 51));
        jButtonNoviVozacPotvrdi.setText("Dodaj vozaca");
        jButtonNoviVozacPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoviVozacPotvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vozacType, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNoviVozacPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vozacType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonNoviVozacPotvrdi, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );

        jTableVozila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "br", "Tablice", "gar. broj"
            }
        ));
        jScrollPane7.setViewportView(jTableVozila);

        jLabelVozac.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelVozac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVozac.setText("-");

        jLabel111.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel111.setText("Tablice");

        jButtonNovoVoziloPotvrdi.setBackground(new java.awt.Color(102, 255, 102));
        jButtonNovoVoziloPotvrdi.setText("Dodaj vozilo");
        jButtonNovoVoziloPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoVoziloPotvrdiActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Obrisi vozilo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel112.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel112.setText("Gar br.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonNoviVozacOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(voziloType, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(garazaType, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonNovoVoziloPotvrdi)
                                                .addGap(85, 85, 85)
                                                .addComponent(jButton2))))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelVozac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVozac, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel108, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voziloType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garazaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovoVoziloPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNoviVozacOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNoviVozacPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviVozacPotvrdiActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            vozacDb.addVozac(vozacType.getText());
            getVozaci();
        }
        vozacType.setText("");
    }//GEN-LAST:event_jButtonNoviVozacPotvrdiActionPerformed

    private void jButtonNoviVozacOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoviVozacOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNoviVozacOdustaniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long id = Long.parseLong(jTableVozaci.getModel().getValueAt(jTableVozaci.getSelectedRow(),2).toString());
        if (JOptionPane.showConfirmDialog(null, "Da li želite da obrisete vozaca ?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            vozacDb.deleteVozac(id);
            getVozaci();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableVozaciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVozaciMouseClicked
        vozac = vozacDb.getVozac(Integer.parseInt(jTableVozaci.getModel().getValueAt(jTableVozaci.getSelectedRow(), 2).toString()));
        System.out.println(jTableVozaci.getModel().getValueAt(jTableVozaci.getSelectedRow(), 2).toString());
        getVozila(vozac);
    }//GEN-LAST:event_jTableVozaciMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        long id = Long.parseLong(jTableVozila.getModel().getValueAt(jTableVozila.getSelectedRow(),3).toString());
        if (JOptionPane.showConfirmDialog(null, "Da li želite da obrisete vozilo ?", "Upozorenje",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        voziloDb.deleteVozilo(id);
        getVozila(vozac);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonNovoVoziloPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoVoziloPotvrdiActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            voziloDb.addVozilo(voziloType.getText(), garazaType.getText(), vozac);
            getVozila(vozac);
        }
        voziloType.setText("");
        garazaType.setText("");
    }//GEN-LAST:event_jButtonNovoVoziloPotvrdiActionPerformed

    public void getVozaci(){
        updateResult(vozacDb.getVozaci());
    }
    
    private void updateResult(List<dbOld.Vozac> result) {
        int i = 0;
        int size = 0;
        
        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAktivan()) {
                size++;
            }
        }
        
        Object[][] obj = new Object[size][3];

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAktivan()) {
                obj[i][0] = i + 1;
                obj[i][1] = result.get(j).getVozac();
                obj[i][2] = result.get(j).getId();
                i++;
            }
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Vozac", "id"});
        this.jTableVozaci.setModel(model);
        this.jTableVozaci.setRowMargin(4);
        this.jTableVozaci.setRowHeight(40);
        this.jTableVozaci.getColumnModel().getColumn(0).setMaxWidth(45);

        this.rowSorter = new TableRowSorter<>(this.jTableVozaci.getModel());
        jTableVozaci.removeColumn(jTableVozaci.getColumnModel().getColumn(2));
        this.jTableVozaci.setRowSorter(rowSorter);
        addFilter();
    }
    
    private void addFilter() {
        vozacType.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = vozacType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = vozacType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
    
    public void getVozila(dbOld.Vozac vozac){
        updateResultVozilo(voziloDb.getVozilaZaVozaca(vozac));
    }
    
    private void updateResultVozilo(List<dbOld.Vozilo> result) {
        int i = 0;
        int size = 0;
        
        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAkivan()) {
                size++;
            }
        }
        
        Object[][] obj = new Object[size][4];

        for (int j = 0; j < result.size(); j++) {
            if (result.get(j).getAkivan()) {
                obj[i][0] = i + 1;
                obj[i][1] = result.get(j).getTablica();
                obj[i][2] = result.get(j).getGaraznibroj();
                obj[i][3] = result.get(j).getId();
                i++;
            }
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Tablica", "gar. br.", "id"});
        jTableVozila.setModel(model);
        jTableVozila.setRowMargin(4);
        jTableVozila.setRowHeight(40);
        jTableVozila.getColumnModel().getColumn(0).setMaxWidth(45);

        this.rowSorter = new TableRowSorter<>(jTableVozila.getModel());
        jTableVozila.removeColumn(jTableVozila.getColumnModel().getColumn(3));
        jTableVozila.setRowSorter(rowSorter);
        addFilterVozila();
    }
     
      private void addFilterVozila() {
        voziloType.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = voziloType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = voziloType.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
    

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField garazaType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonNoviVozacOdustani;
    private javax.swing.JButton jButtonNoviVozacPotvrdi;
    private javax.swing.JButton jButtonNovoVoziloPotvrdi;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabelVozac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableVozaci;
    private javax.swing.JTable jTableVozila;
    private javax.swing.JTextField vozacType;
    private javax.swing.JTextField voziloType;
    // End of variables declaration//GEN-END:variables
    private final VozacService vozacDb;
    private final VoziloService voziloDb;
    private TableRowSorter rowSorter;
    private dbOld.Vozac vozac;
}
