/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package komandniProzori;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import constatnt.Image;
import javax.swing.Timer;
import netvision.NetVision;
import pogon.osnova.Digitalac;

/**
 *
 * @author branko.scekic
 */
public class KomandniProzorPrekidac extends javax.swing.JFrame {

    /**
     * Creates new form PregradniVentil
     *
     * @param x
     * @param y
     * @param img
     * @param tipSlike
     * @param opis
     * @param komandaUkljuci
     * @param komandaIskljuci
     * @param komandaZatvoren
     * @param potvrdaRadaL
     * @param potvrdaRadaD
     * @param greska
     * @param komandaOtvoren
     */
    public KomandniProzorPrekidac(int x, int y, Image img, int tipSlike, 
            String opis, Digitalac komandaUkljuci, Digitalac komandaIskljuci,
            Digitalac komandaOtvoren, Digitalac komandaZatvoren,
            Digitalac potvrdaRadaL, Digitalac potvrdaRadaD, Digitalac greska) {
        initComponents();
        this.setLocation(x - 85, y - 45);
        
        this.img = img;
        this.tipSlike = tipSlike;
        this.komandaUkljuci = komandaUkljuci;
        this.komandaIskljuci = komandaIskljuci;
        this.komandaOtvoren = komandaOtvoren;
        this.komandaZatvoren = komandaZatvoren;
        this.potvrdaRadaL = potvrdaRadaL;
        this.potvrdaRadaD = potvrdaRadaD;
        this.greska = greska;
        this.setTitle(opis);
        this.setVisible(true);
        startScreenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToggleButtonOtvori = new javax.swing.JToggleButton();
        jToggleButtonZatvori = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelVentil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName(""); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jToggleButtonOtvori.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButtonOtvori.setText("Otvori");
        jToggleButtonOtvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOtvoriActionPerformed(evt);
            }
        });

        jToggleButtonZatvori.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButtonZatvori.setText("Zatvori");
        jToggleButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonZatvoriActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Zaustavi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(204, 0, 51));
        jButtonExit.setText("Izlaz");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelVentil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/klapnaMedjupolozaj.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabelVentil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButtonOtvori, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelVentil, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonZatvori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonOtvori, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        timer.stop();
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jToggleButtonOtvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOtvoriActionPerformed
        offsetUklj = komandaUkljuci.getAdresaVrednosti();
        uklj = true;
        isklj = false;
        offsetIsklj = komandaIskljuci.getAdresaVrednosti();
        NetVision.mb.writePrekidac(uklj, offsetUklj, isklj, offsetIsklj);
        //NetVision.mb.writePrekidac(uklj, 0, isklj, 1);
        jToggleButtonZatvori.setSelected(false);
    }//GEN-LAST:event_jToggleButtonOtvoriActionPerformed

    private void jToggleButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonZatvoriActionPerformed
        offsetUklj = komandaUkljuci.getAdresaVrednosti();
        uklj = false;
        isklj = true;
        offsetIsklj = komandaIskljuci.getAdresaVrednosti();
        NetVision.mb.writePrekidac(uklj, offsetUklj, isklj, offsetIsklj);
        //NetVision.mb.writePrekidac(uklj, 0, isklj, 1);
        jToggleButtonOtvori.setSelected(false);
    }//GEN-LAST:event_jToggleButtonZatvoriActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        offsetUklj = komandaUkljuci.getAdresaVrednosti();
        uklj = false;
        isklj = false;
        offsetIsklj = komandaIskljuci.getAdresaVrednosti();
        NetVision.mb.writePrekidac(uklj, offsetUklj, isklj, offsetIsklj);
        //NetVision.mb.writePrekidac(uklj, 0, isklj, 1);
        jToggleButtonOtvori.setSelected(false);
        jToggleButtonZatvori.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        timer.stop();
    }//GEN-LAST:event_formWindowClosed

    public void startScreenRefresh() {
        timer = new Timer(300, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                if(img.getKlapneMedjupolozajSaKrajnjimPrekidacima() == tipSlike){
                //jToggleButtonOtvori.setEnabled(!prekidac.getUklucen().isVrednost() && !prekidac.getGreska().isVrednost());
                //jToggleButtonZatvori.setEnabled(!prekidac.getIskljucen().isVrednost() && !prekidac.getGreska().isVrednost());
                jToggleButtonOtvori.setText("Otvori");
                jToggleButtonZatvori.setText("Zatvori");
                img.setImg(jLabelVentil, komandaOtvoren.isVrednost(), komandaZatvoren.isVrednost(), potvrdaRadaL.isVrednost(), 
                        potvrdaRadaD.isVrednost(), greska.isVrednost());
                
                }else{
                    //jToggleButtonOtvori.setEnabled(!potvrdaRada.isVrednost() && !greska.isVrednost());
                    //jToggleButtonZatvori.setEnabled(potvrdaRada.isVrednost() && !greska.isVrednost());
                    jToggleButtonOtvori.setText("Napred");
                    jToggleButtonZatvori.setText("Nazad");
                    img.setImg(jLabelVentil, potvrdaRadaL.isVrednost(), greska.isVrednost(), tipSlike);
                }
            }
        });
    }
    
    public void timerStart(){
         timer.start();
    }
    
    public void timerStop(){
         timer.stop();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelVentil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButtonOtvori;
    private javax.swing.JToggleButton jToggleButtonZatvori;
    // End of variables declaration//GEN-END:variables
    private Timer timer;
    private final Image img;
    private final int tipSlike ;
    private final Digitalac komandaUkljuci;
    private final Digitalac komandaIskljuci;
    private final Digitalac komandaOtvoren;
    private final Digitalac komandaZatvoren;
    private final Digitalac potvrdaRadaL;
    private final Digitalac potvrdaRadaD;
    private final Digitalac greska;
    private int offsetUklj;
    private int offsetIsklj;
    private boolean uklj;
    private boolean isklj;
}
