/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package komandniProzori;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import constatnt.Image;
import javax.swing.Timer;
import netvision.NetVision;
import pogon.osnova.Digitalac;
/**
 *
 * @author branko.scekic
 */
public class KomandniProzorTasterSaPolozajima extends javax.swing.JFrame {

    /**
     * Creates new form PregradniVentil
     *
     * @param x
     * @param y
     * @param img
     * @param tipSlike
     * @param opis
     * @param komanda
     * @param greska
     * @param potvrdaRada
     */
    public KomandniProzorTasterSaPolozajima(int x, int y, Image img, int tipSlike, String opis, 
            Digitalac komanda, Digitalac potvrdaRada, Digitalac greska,
            Digitalac otvoren, Digitalac zatvoren) {
        initComponents();
        this.setLocation(x - 85, y - 45);
        
        this.img = img;
        this.tipSlike = tipSlike;
        this.komanda = komanda;
        this.potvrdaRada = potvrdaRada;
        this.greska = greska;
        this.otvoren = otvoren;
        this.zatvoren = zatvoren;
        this.setTitle(opis);
        this.setVisible(true);
        startScreenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToggleButtonOtvori = new javax.swing.JToggleButton();
        jToggleButtonZatvori = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabelVentil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ledOtvoren = new eu.hansolo.steelseries.extras.Led();
        jLabel2 = new javax.swing.JLabel();
        ledZatvoren = new eu.hansolo.steelseries.extras.Led();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName(""); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jToggleButtonOtvori.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButtonOtvori.setText("Ukljuci");
        jToggleButtonOtvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOtvoriActionPerformed(evt);
            }
        });

        jToggleButtonZatvori.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButtonZatvori.setText("Iskljuci");
        jToggleButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonZatvoriActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Izvrši");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelVentil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/ZubcOff.png"))); // NOI18N

        jLabel1.setText("Otvoren:");

        jLabel2.setText("Zatvoren");

        ledZatvoren.setLedColor(eu.hansolo.steelseries.tools.LedColor.GREEN_LED);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ledOtvoren, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelVentil, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ledZatvoren, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButtonOtvori, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(ledOtvoren, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ledZatvoren, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelVentil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonZatvori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonOtvori, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jToggleButtonOtvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOtvoriActionPerformed
        offset = komanda.getAdresaVrednosti();
        ukljIsklj = true;
        NetVision.mb.writeMX(ukljIsklj, offset);
        //NetVision.mb.writeMX(ukljIsklj, 0);
        jToggleButtonZatvori.setSelected(false);
    }//GEN-LAST:event_jToggleButtonOtvoriActionPerformed

    private void jToggleButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonZatvoriActionPerformed
        offset = komanda.getAdresaVrednosti();
        ukljIsklj = false;
        NetVision.mb.writeMX(ukljIsklj, offset);
        //NetVision.mb.writeMX(ukljIsklj, 0);
        jToggleButtonOtvori.setSelected(false);
    }//GEN-LAST:event_jToggleButtonZatvoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        timer.stop();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        timer.stop();
    }//GEN-LAST:event_formWindowClosed

    public void startScreenRefresh() {
        timer = new Timer(300, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                    if(img.getKlapne() == tipSlike){
                    //jToggleButtonOtvori.setEnabled(!potvrdaRada.isVrednost() && !greska.isVrednost());
                    //jToggleButtonZatvori.setEnabled(potvrdaRada.isVrednost() && !greska.isVrednost());
                    jToggleButtonOtvori.setText("Otvori");
                    jToggleButtonZatvori.setText("Zatvori");
                    ledOtvoren.setLedOn(otvoren.isVrednost());
                    ledZatvoren.setLedOn(zatvoren.isVrednost());
                    img.setImg(jLabelVentil, potvrdaRada.isVrednost(), greska.isVrednost(), tipSlike);
                    }
                    else{
                         ledOtvoren.setLedOn(otvoren.isVrednost());
                        ledZatvoren.setLedOn(zatvoren.isVrednost());
                        jToggleButtonOtvori.setText("Ukljuci");
                        jToggleButtonZatvori.setText("Iskljuci");
                        img.setImg(jLabelVentil, potvrdaRada.isVrednost(), greska.isVrednost(), tipSlike);
                    }
               
            }
        });
    }
    
    public void timerStart(){
         timer.start();
    }
    
    public void timerStop(){
         timer.stop();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelVentil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButtonOtvori;
    private javax.swing.JToggleButton jToggleButtonZatvori;
    private eu.hansolo.steelseries.extras.Led ledOtvoren;
    private eu.hansolo.steelseries.extras.Led ledZatvoren;
    // End of variables declaration//GEN-END:variables
    private Timer timer;
    private final Image img;
    private final int tipSlike;
    private final Digitalac komanda;
    private final Digitalac potvrdaRada; 
    private final Digitalac greska;
    private final Digitalac otvoren;
    private final Digitalac zatvoren;
    private int offset;
    private boolean ukljIsklj;
}
