/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package komandniProzori;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import constatnt.Image;
import javax.swing.Timer;
import netvision.NetVision;
import pogon.osnova2.FrekfrentniUprosceno;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class KomandniProzorFrekfrentniUprosceno extends javax.swing.JFrame {

    /**
     * Creates new form PregradniVentil
     *
     * @param x
     * @param y
     * @param img
     * @param frekfrentni
     */
    public KomandniProzorFrekfrentniUprosceno( int x, int y, Image img, FrekfrentniUprosceno frekfrentni) {
        initComponents();
        this.setLocation(x - 85, y - 45);
        
        this.setTitle(frekfrentni.getOpis());
        this.setVisible(true);
        this.img = img;
        this.frekfrentni = frekfrentni;
        startScreenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonOtkazi = new javax.swing.JButton();
        jLabelVentil = new javax.swing.JLabel();
        ostvarenaFr = new eu.hansolo.steelseries.gauges.DisplayRectangular();
        jSliderFrekfrencija = new javax.swing.JSlider();
        zadataFr = new eu.hansolo.steelseries.gauges.DisplayRectangular();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName(""); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButtonOtkazi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonOtkazi.setForeground(new java.awt.Color(0, 51, 255));
        jButtonOtkazi.setText("Izlaz");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jLabelVentil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small/frequentOff.png"))); // NOI18N

        ostvarenaFr.setFrameVisible(false);

        jSliderFrekfrencija.setMaximum(50);
        jSliderFrekfrencija.setPaintLabels(true);
        jSliderFrekfrencija.setPaintTicks(true);
        jSliderFrekfrencija.setSnapToTicks(true);
        jSliderFrekfrencija.setValue(0);
        jSliderFrekfrencija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderFrekfrencijaMouseReleased(evt);
            }
        });

        zadataFr.setFrameVisible(false);

        jLabel1.setText("zadata");

        jLabel2.setText("ostvarena");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderFrekfrencija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelVentil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ostvarenaFr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zadataFr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ostvarenaFr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zadataFr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1))
                        .addComponent(jLabelVentil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderFrekfrencija, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         timer.stop();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        timer.stop();
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jSliderFrekfrencijaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderFrekfrencijaMouseReleased
        NetVision.mb.writeMW(jSliderFrekfrencija.getValue(),  frekfrentni.getFrekfrencija().getAdresaVrednosti());
    }//GEN-LAST:event_jSliderFrekfrencijaMouseReleased

    public void startScreenRefresh() {
        timer = new Timer(300, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                zadataFr.setValue(Convert.shiftPointDoubleSign(jSliderFrekfrencija.getValue(), frekfrentni.getFrekfrencija().getBrojDecimala()));
                ostvarenaFr.setValue(Convert.shiftPointDoubleSign(frekfrentni.getFrekfrencija().getVrednost(), frekfrentni.getFrekfrencija().getBrojDecimala()));
                
                //jSliderFrekfrencija.setEnabled(frekfrentni.getPotvrdaRada().isVrednost() && !frekfrentni.getGreska().isVrednost());
                //jToggleButtonUkljuci.setEnabled(!frekfrentni.getPotvrdaRada().isVrednost() && !frekfrentni.getGreska().isVrednost());
                //jToggleButtonIskljuci.setEnabled(frekfrentni.getPotvrdaRada().isVrednost() && !frekfrentni.getGreska().isVrednost());
                img.setImg(jLabelVentil, frekfrentni.getPotvrdaRada().isVrednost(), false, frekfrentni.getTipSlike());
            }
        });
        jSliderFrekfrencija.setValue(frekfrentni.getFrekfrencija().getVrednost());
       
    }
    
    public void timerStart(){
         timer.start();
    }
    
    public void timerStop(){
         timer.stop();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelVentil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderFrekfrencija;
    private eu.hansolo.steelseries.gauges.DisplayRectangular ostvarenaFr;
    private eu.hansolo.steelseries.gauges.DisplayRectangular zadataFr;
    // End of variables declaration//GEN-END:variables

    private final Image img;
    FrekfrentniUprosceno frekfrentni;
    private int offset;
    private boolean ukljIsklj;
    private Timer timer;
}
