/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozori;

import dbService.SarzaService;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class PregledSarziZaOtpremuFrame extends javax.swing.JFrame {

    /**
     * Creates new form pregledSarziZaOtpremuFrame
     * @param sarzaDb
     * @param otprema
     * @param otpremaDb
     */
    public PregledSarziZaOtpremuFrame(SarzaService sarzaDb,  db.Otprema otprema) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.sarzaDb = sarzaDb;
        this.otprema = otprema;
        
        fillData(this.otprema);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableSarza = new javax.swing.JTable();
        jLabel115 = new javax.swing.JLabel();
        brojOtpremaSarza = new javax.swing.JLabel();
        zadatoFk = new javax.swing.JLabel();
        zadatoFS = new javax.swing.JLabel();
        zadato032 = new javax.swing.JLabel();
        zadato0_4 = new javax.swing.JLabel();
        zadato4_8 = new javax.swing.JLabel();
        zadato8_11 = new javax.swing.JLabel();
        zadato11_16 = new javax.swing.JLabel();
        zadato16_22 = new javax.swing.JLabel();
        zadato16_32 = new javax.swing.JLabel();
        zadatoBitumen = new javax.swing.JLabel();
        jButtonPregledOtpreemePoSarzamaOdustani = new javax.swing.JButton();
        jButtonStampajOtpremu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setResizable(false);

        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("Pregled otpreme po šaržama");
        jLabel113.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        jTableSarza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "br", "Fil k izd", "Fil s izd", "0_32 izd", "0_4 izd", "4_8 izd", "8_11 izd", "11_16 izd", "16_22 izd", "16_32 izd", "bitumen", "datum", "vreme"
            }
        ));
        jTableSarza.setFocusable(false);
        jTableSarza.setShowVerticalLines(true);
        jTableSarza.setSurrendersFocusOnKeystroke(true);
        jTableSarza.setToolTipText("");
        jTableSarza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSarzaMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableSarza);

        jLabel115.setText("broj otpreme");

        brojOtpremaSarza.setText("bo");
        brojOtpremaSarza.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        zadatoFk.setText("0");

        zadatoFS.setText("0");

        zadato032.setText("0");

        zadato0_4.setText("0");

        zadato4_8.setText("0");

        zadato8_11.setText("0");

        zadato11_16.setText("0");

        zadato16_22.setText("0");

        zadato16_32.setText("0");

        zadatoBitumen.setText("0");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(zadatoFk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(jLabel115)
                                .addGap(18, 18, 18)
                                .addComponent(brojOtpremaSarza, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(zadatoFS, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zadato032, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zadato0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(zadato4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zadato8_11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(zadato11_16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zadato16_22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zadato16_32, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zadatoBitumen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel115)
                    .addComponent(brojOtpremaSarza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zadatoFk)
                    .addComponent(zadatoFS)
                    .addComponent(zadato032)
                    .addComponent(zadato0_4)
                    .addComponent(zadato4_8)
                    .addComponent(zadato8_11)
                    .addComponent(zadato11_16)
                    .addComponent(zadato16_22)
                    .addComponent(zadato16_32)
                    .addComponent(zadatoBitumen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonPregledOtpreemePoSarzamaOdustani.setText("Odustani");
        jButtonPregledOtpreemePoSarzamaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed(evt);
            }
        });

        jButtonStampajOtpremu.setText("Stampaj otpremu");
        jButtonStampajOtpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStampajOtpremuActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonStampajOtpremu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPregledOtpreemePoSarzamaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPregledOtpreemePoSarzamaOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButtonStampajOtpremu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSarzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSarzaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSarzaMouseClicked

    private void jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed

    private void jButtonStampajOtpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStampajOtpremuActionPerformed
        //dbOld.Radninalog rn = radniNalogDb.getRN(Long.parseLong(brojRadnogNalogaSarza.getText()));
        //otpremnicaStampa.print(rn, otpremaDb.getOtpremaBrRNOtp(rn.getRn(), Long.parseLong(brojOtpremaSarza.getText())), markaBetonaDb.getRecept(1l), kupcidb);
    }//GEN-LAST:event_jButtonStampajOtpremuActionPerformed

  
    
    public void fillData(db.Otprema otprema){
        brojOtpremaSarza.setText(Long.toString(otprema.getId()));
        fillTableSarze(sarzaDb.getSarzeZaOtpremu(otprema.getId()));
    }
    
    private void fillTableSarze(List<db.Sarza> result) {
        int i = 0;
        Object[][] obj = new Object[result.size()][13];
        for (db.Sarza auto : result) {
            obj[i][0] = i + 1;
            obj[i][1] = auto.getFilerkupovniizdato();
            obj[i][2] = auto.getFilersopstveniizdato();
            obj[i][3] = auto.getAgregatizdato032();
            obj[i][4] = auto.getAgregaizdato04();
            obj[i][5] = auto.getAgregatizdato48();
            obj[i][6] = auto.getAgregatizdato811();
            obj[i][7] = auto.getAgregatizdato1116();
            obj[i][8] = auto.getAgregatizdato1622();
            obj[i][9] = auto.getAgregatizdato1632();
            obj[i][10] = auto.getBitumenzadato();
            
            obj[i][11] = Convert.convertDateToStringDate(auto.getDate());
            obj[i][12] = Convert.convertDateToStringTime(auto.getDate());
            i++;
        }

        DefaultTableModel model = new DefaultTableModel(obj, 
                new Object[]{"r.b", "Filer k", "Filer s","0_32 izd", "0_4 izd", "4_8 izd", "8_11 izd", "11_16 izd","16_22 izd", "16_32 izd", "bitumen","datum" , "vreme"});
        jTableSarza.setModel(model);
        jTableSarza.setRowMargin(4);
        jTableSarza.setRowHeight(40);
        jTableSarza.setShowGrid(true);
        jTableSarza.getColumnModel().getColumn(0).setMaxWidth(45);
        jTableSarza.setDefaultEditor(Object.class, null);
    }
    
    
    
  
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brojOtpremaSarza;
    private javax.swing.JButton jButtonPregledOtpreemePoSarzamaOdustani;
    private javax.swing.JButton jButtonStampajOtpremu;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableSarza;
    private javax.swing.JLabel zadato032;
    private javax.swing.JLabel zadato0_4;
    private javax.swing.JLabel zadato11_16;
    private javax.swing.JLabel zadato16_22;
    private javax.swing.JLabel zadato16_32;
    private javax.swing.JLabel zadato4_8;
    private javax.swing.JLabel zadato8_11;
    private javax.swing.JLabel zadatoBitumen;
    private javax.swing.JLabel zadatoFS;
    private javax.swing.JLabel zadatoFk;
    // End of variables declaration//GEN-END:variables
    private final SarzaService sarzaDb;
    private final db.Otprema otprema;
}
