/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozori;

import dbService.SarzaService;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.net.URL;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author branko.scekic
 */
public class PregledPotrosnjeZaOtpremeFrame extends javax.swing.JFrame {

    /**
     * Creates new form pregledSarziZaOtpremuFrame
     *
     * @param sarzaDb
     * @param otprema
     * @param otpremaDb
     */
    public PregledPotrosnjeZaOtpremeFrame(SarzaService sarzaDb, List<db.Otprema> otpreme, String datumOd, String datumDo, String markaAsfalta) {
        initComponents();

        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

        this.sarzaDb = sarzaDb;
        this.otpreme = otpreme;
        
        jLabelDatumOd.setText(datumOd);
        jLabelDatumDo.setText(datumDo);
        jLabelMarkaAsfalta.setText(markaAsfalta);

        fillData(this.otpreme);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        brojOtpremaSarza = new javax.swing.JLabel();
        zadatoFk = new javax.swing.JLabel();
        zadatoFS = new javax.swing.JLabel();
        zadato032 = new javax.swing.JLabel();
        zadato0_4 = new javax.swing.JLabel();
        zadato4_8 = new javax.swing.JLabel();
        zadato8_11 = new javax.swing.JLabel();
        zadato11_16 = new javax.swing.JLabel();
        zadato16_22 = new javax.swing.JLabel();
        zadato16_32 = new javax.swing.JLabel();
        zadatoBitumen = new javax.swing.JLabel();
        zadatoFk1 = new javax.swing.JLabel();
        zadatoFS1 = new javax.swing.JLabel();
        zadato0_5 = new javax.swing.JLabel();
        zadato4_9 = new javax.swing.JLabel();
        zadato8_12 = new javax.swing.JLabel();
        zadato11_17 = new javax.swing.JLabel();
        zadato16_23 = new javax.swing.JLabel();
        zadato16_33 = new javax.swing.JLabel();
        zadato33 = new javax.swing.JLabel();
        zadatoBitumen1 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabelDatumOd = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabelDatumDo = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabelMarkaAsfalta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        zadatoBitumen2 = new javax.swing.JLabel();
        JlabelUkupnoAsfalta = new javax.swing.JLabel();
        zadatoFk2 = new javax.swing.JLabel();
        zadatoFk3 = new javax.swing.JLabel();
        zadatoFk4 = new javax.swing.JLabel();
        zadatoFk5 = new javax.swing.JLabel();
        zadatoFk6 = new javax.swing.JLabel();
        zadatoFk7 = new javax.swing.JLabel();
        zadatoFk8 = new javax.swing.JLabel();
        zadatoFk9 = new javax.swing.JLabel();
        zadatoFk10 = new javax.swing.JLabel();
        zadatoFk11 = new javax.swing.JLabel();
        zadatoFk12 = new javax.swing.JLabel();
        jButtonPregledOtpreemePoSarzamaOdustani = new javax.swing.JButton();
        jButtonStampajOtpremu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setResizable(false);

        jLabel113.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("Izveštaj o potrošnji materijala");

        jLabel115.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel115.setText("broj otprema:");

        brojOtpremaSarza.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        brojOtpremaSarza.setText("0");

        zadatoFk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk.setText("Filer kupovni:");

        zadatoFS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFS.setText("Filer Sopstveni:");

        zadato032.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato032.setText("Frakcija 0_32:");

        zadato0_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato0_4.setText("Frakcija 0_4:");

        zadato4_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato4_8.setText("Frakcija 4_8:");

        zadato8_11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato8_11.setText("Frakcija 8_11:");

        zadato11_16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato11_16.setText("Frakcija 11_16:");

        zadato16_22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato16_22.setText("Frakcija 16_22:");

        zadato16_32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato16_32.setText("Frakcija 16_32:");

        zadatoBitumen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoBitumen.setText("Bitumen:");

        zadatoFk1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk1.setText("Filer kupovni:");

        zadatoFS1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFS1.setText("Filer Sopstveni:");

        zadato0_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato0_5.setText("Frakcija 0_4:");

        zadato4_9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato4_9.setText("Frakcija 4_8:");

        zadato8_12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato8_12.setText("Frakcija 8_11:");

        zadato11_17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato11_17.setText("Frakcija 11_16:");

        zadato16_23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato16_23.setText("Frakcija 16_22:");

        zadato16_33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato16_33.setText("Frakcija 16_32:");

        zadato33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadato33.setText("Frakcija 0_32:");

        zadatoBitumen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoBitumen1.setText("Bitumen:");

        jLabel116.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel116.setText("Datum od:");

        jLabelDatumOd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDatumOd.setText("Datum od:");

        jLabel118.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel118.setText("Datum do:");

        jLabelDatumDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDatumDo.setText("Datum od:");

        jLabel117.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel117.setText("Marka asfalta:");

        jLabelMarkaAsfalta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelMarkaAsfalta.setText("_");

        zadatoBitumen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoBitumen2.setText("Ukupno asfalta:");

        JlabelUkupnoAsfalta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JlabelUkupnoAsfalta.setText("0");

        zadatoFk2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk2.setText("kg");

        zadatoFk3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk3.setText("kg");

        zadatoFk4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk4.setText("kg");

        zadatoFk5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk5.setText("kg");

        zadatoFk6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk6.setText("kg");

        zadatoFk7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk7.setText("kg");

        zadatoFk8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk8.setText("kg");

        zadatoFk9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk9.setText("kg");

        zadatoFk10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk10.setText("kg");

        zadatoFk11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk11.setText("kg");

        zadatoFk12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zadatoFk12.setText("t");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(zadatoFk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadatoFS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato0_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato4_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato8_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato11_17, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                            .addComponent(zadato16_23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato16_33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadatoBitumen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                        .addComponent(jLabel115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(brojOtpremaSarza, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addComponent(zadato16_32, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(zadatoFk9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(zadatoFS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(zadatoFk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zadatoFk2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zadatoFk3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(zadato0_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                            .addComponent(zadato4_8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zadatoFk4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zadatoFk5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(zadato16_22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(zadato8_11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato11_16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zadatoFk6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zadatoFk7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zadatoFk8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addComponent(jLabel118, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDatumDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addComponent(jLabel116, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(zadatoBitumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zadato032, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zadatoFk11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zadatoFk10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(jLabel117, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMarkaAsfalta, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(zadatoBitumen2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JlabelUkupnoAsfalta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zadatoFk12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel116)
                            .addComponent(jLabelDatumOd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel118)
                            .addComponent(jLabelDatumDo)))
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel115)
                        .addComponent(brojOtpremaSarza)))
                .addGap(16, 16, 16)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel117)
                    .addComponent(jLabelMarkaAsfalta))
                .addGap(51, 51, 51)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadatoFk)
                            .addComponent(zadatoFk2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadatoFS)
                            .addComponent(zadatoFk3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato0_4)
                            .addComponent(zadatoFk4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato4_8)
                            .addComponent(zadatoFk5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato8_11)
                            .addComponent(zadatoFk6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato11_16)
                            .addComponent(zadatoFk7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato16_22)
                            .addComponent(zadatoFk8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato16_32)
                            .addComponent(zadatoFk9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadato032)
                            .addComponent(zadatoFk10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zadatoBitumen)
                            .addComponent(zadatoFk11)))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(zadatoFk1)
                        .addGap(18, 18, 18)
                        .addComponent(zadatoFS1)
                        .addGap(18, 18, 18)
                        .addComponent(zadato0_5)
                        .addGap(18, 18, 18)
                        .addComponent(zadato4_9)
                        .addGap(18, 18, 18)
                        .addComponent(zadato8_12)
                        .addGap(18, 18, 18)
                        .addComponent(zadato11_17)
                        .addGap(18, 18, 18)
                        .addComponent(zadato16_23)
                        .addGap(18, 18, 18)
                        .addComponent(zadato16_33)
                        .addGap(18, 18, 18)
                        .addComponent(zadato33)
                        .addGap(18, 18, 18)
                        .addComponent(zadatoBitumen1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JlabelUkupnoAsfalta)
                        .addComponent(zadatoFk12))
                    .addComponent(zadatoBitumen2))
                .addGap(52, 52, 52))
        );

        jButtonPregledOtpreemePoSarzamaOdustani.setText("Odustani");
        jButtonPregledOtpreemePoSarzamaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed(evt);
            }
        });

        jButtonStampajOtpremu.setText("Stampaj Izvestaj");
        jButtonStampajOtpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStampajOtpremuActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonStampajOtpremu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315)
                        .addComponent(jButtonPregledOtpreemePoSarzamaOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonStampajOtpremu, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButtonPregledOtpreemePoSarzamaOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPregledOtpreemePoSarzamaOdustaniActionPerformed

    private void jButtonStampajOtpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStampajOtpremuActionPerformed
       stampajPanel(jPanel26);
    }//GEN-LAST:event_jButtonStampajOtpremuActionPerformed

    public void fillData(List<db.Otprema> otprema) {
        double filerK = 0;
        double filerS = 0;
        double agregat032 = 0;
        double agregat04 = 0;
        double agregat48 = 0;
        double agregat811 = 0;
        double agregat1116 = 0;
        double agregat1622 = 0;
        double agregat1632 = 0;
        double bitumen = 0;
        
        double ukupnoAsfalta = 0;

        List<Long> ids = otprema.stream().map(o -> o.getId()).collect(Collectors.toList());

        List<db.Sarza> sarze = sarzaDb.getSarzeZaOtpreme(ids);

        for (db.Sarza sarza : sarze) {
            filerK += sarza.getFilerkupovniizdato();
            filerS += sarza.getFilersopstveniizdato();
            agregat04 += sarza.getAgregaizdato04();
            agregat48 += sarza.getAgregatizdato48();
            agregat811 += sarza.getAgregatizdato811();
            agregat1116 += sarza.getAgregatizdato1116();
            agregat1622 += sarza.getAgregatizdato1622();
            agregat1632 += sarza.getAgregatizdato1632();
            agregat032 += sarza.getAgregatizdato032();
            bitumen += sarza.getBitumenizdato();
        }
        
        ukupnoAsfalta =  filerK + filerS + agregat04 + agregat48 +
            agregat811 + agregat1116 + agregat1622 + agregat1632 +
            agregat032 + bitumen;
        
        ukupnoAsfalta = ukupnoAsfalta / 1000;
        
        JlabelUkupnoAsfalta.setText(String.format("%.2f", ukupnoAsfalta));
        
        brojOtpremaSarza.setText(String.format("%d", otprema.size()));

        zadatoFk.setText(String.format("%.2f", filerK));
        zadatoFS.setText(String.format("%.2f", filerS));

        zadato0_4.setText(String.format("%.2f", agregat04));
        zadato4_8.setText(String.format("%.2f", agregat48));
        zadato8_11.setText(String.format("%.2f", agregat811));
        zadato11_16.setText(String.format("%.2f", agregat1116));
        zadato16_22.setText(String.format("%.2f", agregat1622));
        zadato16_32.setText(String.format("%.2f", agregat1632));
        zadato032.setText(String.format("%.2f", agregat032));

        zadatoBitumen.setText(String.format("%.2f", bitumen));
        
        

    }

    public void stampajPanel(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Štampa Izvestaj");

        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                // pomeranje grafike tako da stane na marginu
                Graphics2D g2d = (Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                // skaliranje ako želiš da stane na stranicu
                double scaleX = pageFormat.getImageableWidth() / panel.getWidth();
                double scaleY = pageFormat.getImageableHeight() / panel.getHeight();
                double scale = Math.min(scaleX, scaleY);
                g2d.scale(scale, scale);

                panel.printAll(g2d); // štampa ceo JPanel
                return PAGE_EXISTS;
            }
        });

        boolean doStampanja = printerJob.printDialog(); // prikazuje dijalog štampe
        if (doStampanja) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(panel, "Greška prilikom štampe: " + ex.getMessage());
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelUkupnoAsfalta;
    private javax.swing.JLabel brojOtpremaSarza;
    private javax.swing.JButton jButtonPregledOtpreemePoSarzamaOdustani;
    private javax.swing.JButton jButtonStampajOtpremu;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabelDatumDo;
    private javax.swing.JLabel jLabelDatumOd;
    private javax.swing.JLabel jLabelMarkaAsfalta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel zadato032;
    private javax.swing.JLabel zadato0_4;
    private javax.swing.JLabel zadato0_5;
    private javax.swing.JLabel zadato11_16;
    private javax.swing.JLabel zadato11_17;
    private javax.swing.JLabel zadato16_22;
    private javax.swing.JLabel zadato16_23;
    private javax.swing.JLabel zadato16_32;
    private javax.swing.JLabel zadato16_33;
    private javax.swing.JLabel zadato33;
    private javax.swing.JLabel zadato4_8;
    private javax.swing.JLabel zadato4_9;
    private javax.swing.JLabel zadato8_11;
    private javax.swing.JLabel zadato8_12;
    private javax.swing.JLabel zadatoBitumen;
    private javax.swing.JLabel zadatoBitumen1;
    private javax.swing.JLabel zadatoBitumen2;
    private javax.swing.JLabel zadatoFS;
    private javax.swing.JLabel zadatoFS1;
    private javax.swing.JLabel zadatoFk;
    private javax.swing.JLabel zadatoFk1;
    private javax.swing.JLabel zadatoFk10;
    private javax.swing.JLabel zadatoFk11;
    private javax.swing.JLabel zadatoFk12;
    private javax.swing.JLabel zadatoFk2;
    private javax.swing.JLabel zadatoFk3;
    private javax.swing.JLabel zadatoFk4;
    private javax.swing.JLabel zadatoFk5;
    private javax.swing.JLabel zadatoFk6;
    private javax.swing.JLabel zadatoFk7;
    private javax.swing.JLabel zadatoFk8;
    private javax.swing.JLabel zadatoFk9;
    // End of variables declaration//GEN-END:variables
    private final SarzaService sarzaDb;
    private final List<db.Otprema> otpreme;
}
