/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozori;


import dbService.PreletiService;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import netvision.NetVision;
import pogon.Pogon;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class PreletiFrame extends javax.swing.JFrame {

    /**
     * Creates new form PreletnaMasaFrame
     * @param pogon
     */
    public PreletiFrame(Pogon pogon) {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        //this.preletiDb = preletiDb;
        this.pogon = pogon;
        getPreleti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButtonPreletiOdustani = new javax.swing.JButton();
        jButtonPreletiSacuvaj = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        AOFinoDoziranjeFrakcija1 = new javax.swing.JSpinner();
        AOPreletFrakcija1 = new javax.swing.JSpinner();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        AOPreletFrakcija2 = new javax.swing.JSpinner();
        AOFinoDoziranjeFrakcija2 = new javax.swing.JSpinner();
        jLabel88 = new javax.swing.JLabel();
        AOFinoDoziranjeFrakcija3 = new javax.swing.JSpinner();
        jLabel89 = new javax.swing.JLabel();
        AOPreletFrakcija3 = new javax.swing.JSpinner();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        AOPreletFrakcija4 = new javax.swing.JSpinner();
        AOFinoDoziranjeFrakcija4 = new javax.swing.JSpinner();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        AOFinoDoziranjeFrakcija5 = new javax.swing.JSpinner();
        AOPreletFrakcija5 = new javax.swing.JSpinner();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        AOFinoDoziranjeFrakcija6 = new javax.swing.JSpinner();
        AOPreletFrakcija6 = new javax.swing.JSpinner();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        AOFinoDoziranjeFrakcija7 = new javax.swing.JSpinner();
        AOPreletFrakcija7 = new javax.swing.JSpinner();
        jLabel98 = new javax.swing.JLabel();
        AOPreletKupovniFiler = new javax.swing.JSpinner();
        jLabel99 = new javax.swing.JLabel();
        AOPreletSopstveniFiler = new javax.swing.JSpinner();
        jLabel100 = new javax.swing.JLabel();
        AOPreletBitumen = new javax.swing.JSpinner();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setResizable(false);

        jLabel76.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("Preletna masa");

        jButtonPreletiOdustani.setText("Odustani");
        jButtonPreletiOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreletiOdustaniActionPerformed(evt);
            }
        });

        jButtonPreletiSacuvaj.setText("Sacuvaj");
        jButtonPreletiSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreletiSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonPreletiSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPreletiOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPreletiSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPreletiOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel77.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel77.setText("1. Fino doziranje frakcije 1");

        jLabel78.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("2. Prelet frakcija 1");

        AOFinoDoziranjeFrakcija1.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        AOPreletFrakcija1.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel86.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel86.setText("3. Fino doziranje frakcije 2");

        jLabel87.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel87.setText("4. Prelet frakcija 2");

        AOPreletFrakcija2.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        AOFinoDoziranjeFrakcija2.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel88.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel88.setText("5. Fino doziranje frakcije 3");

        AOFinoDoziranjeFrakcija3.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel89.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel89.setText("6. Prelet frakcija 3");

        AOPreletFrakcija3.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel90.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel90.setText("7. Fino doziranje frakcije 4");

        jLabel91.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel91.setText("8. Prelet frakcija 4");

        AOPreletFrakcija4.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        AOFinoDoziranjeFrakcija4.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel92.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel92.setText("9. Fino doziranje frakcije 5");

        jLabel93.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel93.setText("10. Prelet frakcija 5");

        AOFinoDoziranjeFrakcija5.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        AOPreletFrakcija5.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel94.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel94.setText("11. Fino doziranje frakcije 6");

        jLabel95.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel95.setText("12. Prelet frakcija 6");

        AOFinoDoziranjeFrakcija6.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        AOPreletFrakcija6.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel96.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel96.setText("13. Fino doziranje frakcije 7");

        jLabel97.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel97.setText("14. Prelet frakcija 7");

        AOFinoDoziranjeFrakcija7.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        AOPreletFrakcija7.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel98.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel98.setText("15. Prelet kupovnog filera");

        AOPreletKupovniFiler.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel99.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel99.setText("16. Prelet sopstvenog filera");

        AOPreletSopstveniFiler.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        jLabel100.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel100.setText("17. Prelet bitumena");

        AOPreletBitumen.setModel(new javax.swing.SpinnerNumberModel(1.0d, -10000.0d, 10000.0d, 1.0d));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel90)
                                .addGap(75, 75, 75))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel91)
                                .addGap(134, 134, 134)))
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AOPreletFrakcija4)
                            .addComponent(AOFinoDoziranjeFrakcija4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel86)
                                        .addComponent(jLabel87))
                                    .addGap(38, 38, 38))
                                .addGroup(jPanel16Layout.createSequentialGroup()
                                    .addComponent(jLabel88)
                                    .addGap(75, 75, 75)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel89)
                                .addGap(134, 134, 134)))
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AOPreletFrakcija3)
                            .addComponent(AOFinoDoziranjeFrakcija3)
                            .addComponent(AOPreletFrakcija2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AOFinoDoziranjeFrakcija2)
                            .addComponent(AOFinoDoziranjeFrakcija1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AOPreletFrakcija1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AOPreletBitumen, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AOPreletSopstveniFiler, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AOPreletKupovniFiler, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AOPreletFrakcija7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AOFinoDoziranjeFrakcija7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel92))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AOPreletFrakcija5)
                            .addComponent(AOFinoDoziranjeFrakcija5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AOPreletFrakcija6)
                            .addComponent(AOFinoDoziranjeFrakcija6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AOFinoDoziranjeFrakcija1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AOPreletFrakcija1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AOFinoDoziranjeFrakcija5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel92))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AOPreletFrakcija5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel93))))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AOFinoDoziranjeFrakcija2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel86))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AOPreletFrakcija2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel87)
                                            .addComponent(jLabel95)))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AOFinoDoziranjeFrakcija6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel94))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AOPreletFrakcija6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AOFinoDoziranjeFrakcija3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel88))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AOPreletFrakcija3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel89)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AOFinoDoziranjeFrakcija7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel96))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AOPreletFrakcija7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel97))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AOFinoDoziranjeFrakcija4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel90))
                            .addComponent(jLabel98)))
                    .addComponent(AOPreletKupovniFiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AOPreletFrakcija4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel91)
                    .addComponent(AOPreletSopstveniFiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel99))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AOPreletBitumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jMenu6.setText("rezervna kopija");

        jMenuItem6.setText("Ucitaj iz baze");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPreletiOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreletiOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPreletiOdustaniActionPerformed

    private void jButtonPreletiSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreletiSacuvajActionPerformed
       if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setPreleti();
            //preletiDb.setPreleti();
        }
    }//GEN-LAST:event_jButtonPreletiSacuvajActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //preletiDb.getPreleti();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija1;
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija2;
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija3;
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija4;
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija5;
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija6;
    private javax.swing.JSpinner AOFinoDoziranjeFrakcija7;
    private javax.swing.JSpinner AOPreletBitumen;
    private javax.swing.JSpinner AOPreletFrakcija1;
    private javax.swing.JSpinner AOPreletFrakcija2;
    private javax.swing.JSpinner AOPreletFrakcija3;
    private javax.swing.JSpinner AOPreletFrakcija4;
    private javax.swing.JSpinner AOPreletFrakcija5;
    private javax.swing.JSpinner AOPreletFrakcija6;
    private javax.swing.JSpinner AOPreletFrakcija7;
    private javax.swing.JSpinner AOPreletKupovniFiler;
    private javax.swing.JSpinner AOPreletSopstveniFiler;
    private javax.swing.JButton jButtonPreletiOdustani;
    private javax.swing.JButton jButtonPreletiSacuvaj;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    // End of variables declaration//GEN-END:variables

   // private final PreletiService preletiDb;
    private final Pogon pogon;
    
    
     private void setPreleti() {
         
        int[] podaci = {
            Convert.objectToInt(AOFinoDoziranjeFrakcija1.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija1().getBrojDecimala()),
            Convert.objectToInt(AOPreletFrakcija1.getValue(), pogon.getPreleti().getPreletFrakcija1().getBrojDecimala()),
            Convert.objectToInt(AOFinoDoziranjeFrakcija2.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija2().getBrojDecimala()),
            Convert.objectToInt(AOPreletFrakcija2.getValue(), pogon.getPreleti().getPreletFrakcija2().getBrojDecimala()),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOFinoDoziranjeFrakcija3.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija3().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletFrakcija3.getValue(), pogon.getPreleti().getPreletFrakcija3().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOFinoDoziranjeFrakcija4.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija4().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletFrakcija4.getValue(), pogon.getPreleti().getPreletFrakcija4().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOFinoDoziranjeFrakcija5.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija5().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletFrakcija5.getValue(), pogon.getPreleti().getPreletFrakcija5().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOFinoDoziranjeFrakcija6.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija6().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletFrakcija6.getValue(), pogon.getPreleti().getPreletFrakcija6().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOFinoDoziranjeFrakcija7.getValue(), pogon.getPreleti().getFinoDoziranjeFrakcija7().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletFrakcija7.getValue(), pogon.getPreleti().getPreletFrakcija7().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletKupovniFiler.getValue(), pogon.getPreleti().getPreletKupovnogFilera().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletSopstveniFiler.getValue(), pogon.getPreleti().getPreletSopstvenogFilera().getBrojDecimala()),0),
            (int)Convert.shiftPointDoubleSign(Convert.objectToInt(AOPreletBitumen.getValue(), pogon.getPreleti().getPreletBitumena().getBrojDecimala()),0)
        };
        
        NetVision.mb.writeMWs(podaci, pogon.getPreleti().getFinoDoziranjeFrakcija1().getAdresaVrednosti());

    }
     
     public void getPreleti() {
       
        AOFinoDoziranjeFrakcija1.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija1().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija1().getBrojDecimala()));
        AOPreletFrakcija1.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija1().getVrednost(), pogon.getPreleti().getPreletFrakcija1().getBrojDecimala()));
        AOFinoDoziranjeFrakcija2.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija2().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija2().getBrojDecimala()));
        AOPreletFrakcija2.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija2().getVrednost(), pogon.getPreleti().getPreletFrakcija2().getBrojDecimala()));
        AOFinoDoziranjeFrakcija3.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija3().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija3().getBrojDecimala()));
        AOPreletFrakcija3.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija3().getVrednost(), pogon.getPreleti().getPreletFrakcija3().getBrojDecimala()));
        AOFinoDoziranjeFrakcija4.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija4().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija4().getBrojDecimala()));
        AOPreletFrakcija4.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija4().getVrednost(), pogon.getPreleti().getPreletFrakcija4().getBrojDecimala()));
        AOFinoDoziranjeFrakcija5.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija5().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija5().getBrojDecimala()));
        AOPreletFrakcija5.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija5().getVrednost(), pogon.getPreleti().getPreletFrakcija5().getBrojDecimala()));
        AOFinoDoziranjeFrakcija6.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija6().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija6().getBrojDecimala()));
        AOPreletFrakcija6.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija6().getVrednost(), pogon.getPreleti().getPreletFrakcija6().getBrojDecimala()));
        AOFinoDoziranjeFrakcija7.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getFinoDoziranjeFrakcija7().getVrednost(), pogon.getPreleti().getFinoDoziranjeFrakcija7().getBrojDecimala()));
        AOPreletFrakcija7.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletFrakcija7().getVrednost(), pogon.getPreleti().getPreletFrakcija7().getBrojDecimala()));
        AOPreletKupovniFiler.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletKupovnogFilera().getVrednost(), pogon.getPreleti().getPreletKupovnogFilera().getBrojDecimala()));
        AOPreletSopstveniFiler.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletSopstvenogFilera().getVrednost(), pogon.getPreleti().getPreletSopstvenogFilera().getBrojDecimala()));
        AOPreletBitumen.setValue(Convert.shiftPointDoubleSign(pogon.getPreleti().getPreletBitumena().getVrednost(), pogon.getPreleti().getPreletBitumena().getBrojDecimala()));
    }

   
}
