/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netvision.prozori;

import dbService.ZbirniParametriService;
import java.net.URL;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import netvision.NetVision;
import pogon.Pogon;
import utils.Convert;

/**
 *
 * @author branko.scekic
 */
public class ZbirniParametriFrame extends javax.swing.JFrame {

    /**
     * Creates new form ZbirniParametriFrame
     *
     * @param zbirniParametriDb
     * @param pogon
     */
    public ZbirniParametriFrame(Pogon pogon, ZbirniParametriService zbirniParametriDb) {
        initComponents();

        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

        this.zbirniParametriDb =zbirniParametriDb;
        this.pogon = pogon;
        getZbirniParametri();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel20 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButtonParametriOdustani = new javax.swing.JButton();
        jButtonPreletiSacuvaj1 = new javax.swing.JButton();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        AOParametriVremeSmirivanjaVageFrakcije = new javax.swing.JSpinner();
        AOParametriVremeSmirivanjaVageFilera = new javax.swing.JSpinner();
        AOParametriVremeSmirivanjaVageBitumena = new javax.swing.JSpinner();
        AOParametriZadrskaNaDoziranjeFilera = new javax.swing.JSpinner();
        AOParametriZadrskaNaDoziranjeBitumena = new javax.swing.JSpinner();
        AOParametriVremePrskanjaNaftomKorpe = new javax.swing.JSpinner();
        AOParametriVremePrskanjaNaftomVagona = new javax.swing.JSpinner();
        AOParametriVremeMesanjaMesalice = new javax.swing.JSpinner();
        AOParametriVremePraznjenjaMesalice = new javax.swing.JSpinner();
        AOParametriKapacitetMesalice = new javax.swing.JSpinner();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setResizable(false);

        jLabel86.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("Zbirni parametri");

        jButtonParametriOdustani.setText("Odustani");
        jButtonParametriOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParametriOdustaniActionPerformed(evt);
            }
        });

        jButtonPreletiSacuvaj1.setText("Sacuvaj");
        jButtonPreletiSacuvaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreletiSacuvaj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPreletiSacuvaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonParametriOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonParametriOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButtonPreletiSacuvaj1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel87.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel87.setText("- Vreme smirivanja vage frakcije (sec)");

        jLabel88.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel88.setText("- Vreme smirivanja vage filera  (sec)");

        jLabel89.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel89.setText("- Vreme smirivanja vage bitumena (sec)");

        jLabel90.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel90.setText("- Zadrska na doziranje filera (sec)");

        jLabel91.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel91.setText("- Zadrska na doziranje bitumena (sec)");

        jLabel92.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel92.setText("- Vreme prskanja naftom korpom (sec)");

        jLabel93.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel93.setText("- Vreme prskanja naftom vagona (sec)");

        jLabel94.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel94.setText("- Vreme mešanja mešalice  (sec)");

        jLabel95.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel95.setText("- Vreme praznjenja mesalice  (sec)");

        jLabel100.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel100.setText("- Kapacitet mešalice (kg)");

        AOParametriVremeSmirivanjaVageFrakcije.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriVremeSmirivanjaVageFilera.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriVremeSmirivanjaVageBitumena.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriZadrskaNaDoziranjeFilera.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriZadrskaNaDoziranjeBitumena.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriVremePrskanjaNaftomKorpe.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriVremePrskanjaNaftomVagona.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriVremeMesanjaMesalice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriVremePraznjenjaMesalice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 30000.0d, 1.0d));

        AOParametriKapacitetMesalice.setModel(new javax.swing.SpinnerNumberModel(1, 0, 1500, 1));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AOParametriVremePraznjenjaMesalice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremeMesanjaMesalice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremeSmirivanjaVageFrakcije, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AOParametriVremeSmirivanjaVageFilera, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremeSmirivanjaVageBitumena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriZadrskaNaDoziranjeFilera, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriZadrskaNaDoziranjeBitumena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremePrskanjaNaftomKorpe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremePrskanjaNaftomVagona, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel100, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AOParametriKapacitetMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriVremeSmirivanjaVageFrakcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriVremeSmirivanjaVageFilera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriVremeSmirivanjaVageBitumena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AOParametriZadrskaNaDoziranjeFilera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AOParametriKapacitetMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriZadrskaNaDoziranjeBitumena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriVremePrskanjaNaftomKorpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AOParametriVremePrskanjaNaftomVagona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriVremeMesanjaMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOParametriVremePraznjenjaMesalice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenu7.setText("Rezervna kopija");

        jMenuItem7.setText("preuzmi");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuBar3.add(jMenu7);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        List<db.Zbirniparametri> zp = zbirniParametriDb.getZbirniParametri();
        AOParametriVremeSmirivanjaVageFrakcije.setValue(zp.get(0).getVremesmirivanjavagefrakcije());
        AOParametriVremeSmirivanjaVageFilera.setValue(zp.get(0).getVremepraznjenjavagefrakcije());
        AOParametriVremeSmirivanjaVageBitumena.setValue(zp.get(0).getVremepraznjenjakosetrake());
        AOParametriZadrskaNaDoziranjeFilera.setValue(zp.get(0).getKontrolnovremekosetrake());
        AOParametriZadrskaNaDoziranjeBitumena.setValue(zp.get(0).getZadrskanadoziranjevode());
        AOParametriVremePrskanjaNaftomKorpe.setValue(zp.get(0).getZadrskanadoziranjecementa());
        AOParametriVremePrskanjaNaftomVagona.setValue(zp.get(0).getVrememesanjamaterijala());
        AOParametriVremeMesanjaMesalice.setValue(zp.get(0).getPocetnootvaranjemesalice());
        AOParametriVremePraznjenjaMesalice.setValue(zp.get(0).getVremepocetnogpraznjenjamesalice());
        //AOParametriVremeKonacnogPraznjenjaMesalice.setValue(zp.get(0).getVremekonacnogpraznjenjamesalice());
        //AOParametriVremeIspiranjaVageAditiva.setValue(zp.get(0).getVremeispiranjavageaditiva());
        //AOParametriPauzaFluidizacije.setValue(zp.get(0).getPauzafluidizacije());
        //AOParametriRadFluidizacije.setValue(zp.get(0).getRadfluidizacije());
        AOParametriKapacitetMesalice.setValue(zp.get(0).getKapacitetmesalice());
        //AOParametriZadrskaNaStartKoseTrake.setValue(zp.get(0).getZadrskanastartkosetrake());
        //AOParametriVremeSmirivanjaVageAditiva.setValue(zp.get(0).getVremesmirivanjavageaditiva());
        //AOParametriVremeSmirivanjaVageCementa.setValue(zp.get(0).getVremesmirivanjavagecementa());
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButtonParametriOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParametriOdustaniActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonParametriOdustaniActionPerformed

    private void jButtonPreletiSacuvaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreletiSacuvaj1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Da li želite da sačuvate?", "Upozorenje",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setZbirniParametri();
            /*      treba srediti upis u bazu, promenjeni su parametri
            zbirniParametriDb.saveZbirniParametri(
                    Convert.stringToDouble(AOParametriVremeSmirivanjaVageFrakcije.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremeSmirivanjaVageFilera.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremeSmirivanjaVageBitumena.getValue().toString()),
                    Convert.stringToDouble(AOParametriZadrskaNaDoziranjeFilera.getValue().toString()),
                    Convert.stringToDouble(AOParametriZadrskaNaDoziranjeBitumena.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremePrskanjaNaftomKorpe.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremePrskanjaNaftomVagona.getValue().toString()),
                    Convert.stringToDouble(AOParametriPocetnoOtvaranjeMesalice.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremePocetnogPraznjenjaMesalice.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremeKonacnogPraznjenjaMesalice.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremeIspiranjaVageAditiva.getValue().toString()),
                    Convert.stringToDouble(AOParametriPauzaFluidizacije.getValue().toString()),
                    Convert.stringToDouble(AOParametriRadFluidizacije.getValue().toString()),
                    Integer.parseInt(AOParametriKapacitetMesalice.getValue().toString()),
                    Convert.stringToDouble(AOParametriZadrskaNaStartKoseTrake.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremeSmirivanjaVageAditiva.getValue().toString()),
                    Convert.stringToDouble(AOParametriVremeSmirivanjaVageCementa.getValue().toString()));
            */
        }
    }//GEN-LAST:event_jButtonPreletiSacuvaj1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AOParametriKapacitetMesalice;
    private javax.swing.JSpinner AOParametriVremeMesanjaMesalice;
    private javax.swing.JSpinner AOParametriVremePraznjenjaMesalice;
    private javax.swing.JSpinner AOParametriVremePrskanjaNaftomKorpe;
    private javax.swing.JSpinner AOParametriVremePrskanjaNaftomVagona;
    private javax.swing.JSpinner AOParametriVremeSmirivanjaVageBitumena;
    private javax.swing.JSpinner AOParametriVremeSmirivanjaVageFilera;
    private javax.swing.JSpinner AOParametriVremeSmirivanjaVageFrakcije;
    private javax.swing.JSpinner AOParametriZadrskaNaDoziranjeBitumena;
    private javax.swing.JSpinner AOParametriZadrskaNaDoziranjeFilera;
    private javax.swing.JButton jButtonParametriOdustani;
    private javax.swing.JButton jButtonPreletiSacuvaj1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    // End of variables declaration//GEN-END:variables
    private final ZbirniParametriService zbirniParametriDb;
    private final Pogon pogon;

    public void setZbirniParametri() {
        
        pogon.getParametri().setKapacitetMesalice(Integer.valueOf(AOParametriKapacitetMesalice.getValue().toString()));
        
        int[] podaci1 = {
            Convert.objectToInt(AOParametriVremeSmirivanjaVageFrakcije.getValue(),pogon.getParametri().getVremeSmirivanjaVageFrakcije().getBrojDecimala()),
            Convert.objectToInt(AOParametriVremeSmirivanjaVageFilera.getValue(), pogon.getParametri().getVremeSmirivanjaVageFilera().getBrojDecimala()),
            Convert.objectToInt(AOParametriVremeSmirivanjaVageBitumena.getValue(), pogon.getParametri().getVremeSmirivanjaVageBitumena().getBrojDecimala())};
        
        int[] podaci2 = {
            Convert.objectToInt(AOParametriZadrskaNaDoziranjeFilera.getValue(),pogon.getParametri().getZadrskaZaDoziranjeFilera().getBrojDecimala()),
            Convert.objectToInt(AOParametriZadrskaNaDoziranjeBitumena.getValue(),pogon.getParametri().getZadrskaZaDoziranjeBitumena().getBrojDecimala()),
            Convert.objectToInt(AOParametriVremeMesanjaMesalice.getValue(),pogon.getParametri().getVremeMesanjaMesalice().getBrojDecimala()),
            Convert.objectToInt(AOParametriVremePraznjenjaMesalice.getValue(),pogon.getParametri().getVremePraznjenjaMesalice().getBrojDecimala())};
            
        
        int[] podaci3 = {
            Convert.objectToInt(AOParametriVremePrskanjaNaftomKorpe.getValue(),pogon.getParametri().getVremePrskanjaNaftomKorpe().getBrojDecimala()),
            Convert.objectToInt(AOParametriVremePrskanjaNaftomVagona.getValue(), pogon.getParametri().getVremePrskanjaNaftomVagona().getBrojDecimala())};
        
        NetVision.mb.writeThreeRegisters(podaci1, pogon.getParametri().getVremeSmirivanjaVageFrakcije().getAdresaVrednosti(), 
                podaci2, pogon.getParametri().getZadrskaZaDoziranjeFilera().getAdresaVrednosti(), 
                podaci3, pogon.getParametri().getVremePrskanjaNaftomKorpe().getAdresaVrednosti());
    }

    public void getZbirniParametri() {
        
        AOParametriVremeSmirivanjaVageFrakcije.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeSmirivanjaVageFrakcije().getVrednost(), pogon.getParametri().getVremeSmirivanjaVageFrakcije().getBrojDecimala()));
        AOParametriVremeSmirivanjaVageFilera.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeSmirivanjaVageFilera().getVrednost(), pogon.getParametri().getVremeSmirivanjaVageFilera().getBrojDecimala()));
        AOParametriVremeSmirivanjaVageBitumena.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeSmirivanjaVageBitumena().getVrednost(), pogon.getParametri().getVremeSmirivanjaVageBitumena().getBrojDecimala()));

        AOParametriZadrskaNaDoziranjeFilera.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getZadrskaZaDoziranjeFilera().getVrednost(), pogon.getParametri().getZadrskaZaDoziranjeFilera().getBrojDecimala()));
        AOParametriZadrskaNaDoziranjeBitumena.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getZadrskaZaDoziranjeBitumena().getVrednost(), pogon.getParametri().getZadrskaZaDoziranjeBitumena().getBrojDecimala()));
        AOParametriVremeMesanjaMesalice.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeMesanjaMesalice().getVrednost(), pogon.getParametri().getVremeMesanjaMesalice().getBrojDecimala()));
        AOParametriVremePraznjenjaMesalice.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremePraznjenjaMesalice().getVrednost(), pogon.getParametri().getVremePraznjenjaMesalice().getBrojDecimala()));
        
        AOParametriVremePrskanjaNaftomKorpe.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremePrskanjaNaftomKorpe().getVrednost(), pogon.getParametri().getVremePrskanjaNaftomKorpe().getBrojDecimala()));
        AOParametriVremePrskanjaNaftomVagona.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremePrskanjaNaftomVagona().getVrednost(), pogon.getParametri().getVremePrskanjaNaftomVagona().getBrojDecimala()));
        
        
       // AOParametriPocetnoOtvaranjeMesalice.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getPocetnoOtvaranjeMesalice(), pogon.getParametri().getBrDec()));
       // AOParametriVremePocetnogPraznjenjaMesalice.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremePocetnogPraznjenjaMesalice(), pogon.getParametri().getBrDec()));

       // AOParametriVremeKonacnogPraznjenjaMesalice.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremePraznjenjaMesalice(), pogon.getParametri().getBrDec()));
       // AOParametriVremeIspiranjaVageAditiva.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeIspiranjaVageAditiva(), pogon.getParametri().getBrDec()));
       // AOParametriPauzaFluidizacije.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getPauzaFluidizacije(), pogon.getParametri().getBrDec()));

       // AOParametriRadFluidizacije.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getRadFluidizacije(), pogon.getParametri().getBrDec()));
        AOParametriKapacitetMesalice.setValue(pogon.getParametri().getKapacitetMesalice());
       // AOParametriZadrskaNaStartKoseTrake.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getZadrskaNaStartKoseTrake(), pogon.getParametri().getBrDec()));

       // AOParametriVremeSmirivanjaVageAditiva.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeSmirivanjaVageAditiva(), pogon.getParametri().getBrDec()));
       // AOParametriVremeSmirivanjaVageCementa.setValue(Convert.shiftPointDoubleSign(pogon.getParametri().getVremeSmirivanjaVageCementa(), pogon.getParametri().getBrDec()));
         
    }

   
}
