/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import constatnt.Image;
import dbService.OtpremaService;
import dbService.RecepturaService;
import dbService.SarzaService;
import dbService.ZbirniParametriService;
import frame.internalFrame.InternalFrameGlavnaSlika1;
import frame.internalFrame.InternalFrameGlavnaSlika2;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import netvision.prozori.PregledOtpremaFrame;
import netvision.prozori.PregledSarziZaOtpremuFrame;
import netvision.prozori.PreletiFrame;
import netvision.prozori.RecepturaFrame;
import netvision.prozori.ZbirniParametriFrame;
import pogon.Pogon;
import proracun.ProracunBrSarzi;

/**
 *
 * @author Branko
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     * @param pogon
     * @param recepturaDb
     * @param zbirniParametriDb
     * @param otpremaDb
     */
    public MainFrame(Pogon pogon, RecepturaService recepturaDb, ZbirniParametriService zbirniParametriDb, 
            OtpremaService otpremaDb, SarzaService sarzaDb) {
        initComponents();
        URL iconURL = getClass().getResource("/img/logo.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        proracunKomponenti = new ProracunBrSarzi();
        this.RecepturaDb = recepturaDb;
        this.zbirniParametriDb = zbirniParametriDb;
        this.otpremaDb = otpremaDb;
        this.sarzaDb = sarzaDb;
        this.pogon = pogon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        ItemParametriZbirni = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jItemSlika2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetVision");
        setLocationByPlatform(true);
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1950, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );

        jMenuBar1.setFocusable(false);

        jMenu1.setText("Slike");

        jMenuItem2.setText("Slika 1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Slika 2");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        ItemParametriZbirni.setText("Parametri");

        jMenuItem4.setText("Preleti");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ItemParametriZbirni.add(jMenuItem4);

        jMenuItem1.setText("Zbirni parametri");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ItemParametriZbirni.add(jMenuItem1);

        jItemSlika2.setText("Receptura");
        jItemSlika2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemSlika2ActionPerformed(evt);
            }
        });
        ItemParametriZbirni.add(jItemSlika2);

        jMenuBar1.add(ItemParametriZbirni);

        jMenu2.setText("Potrosnja");

        jMenuItem5.setText("Otpreme");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setBounds(0, 0, 1950, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if (zbirniParametri != null) {
            zbirniParametri.dispose();   
        }
        zbirniParametri = new ZbirniParametriFrame(pogon, zbirniParametriDb);
        zbirniParametri.getZbirniParametri();
        zbirniParametri.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jItemSlika2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemSlika2ActionPerformed
         if (recepturaFrame != null) {
            recepturaFrame.dispose();   
        }
        recepturaFrame = new RecepturaFrame(RecepturaDb);
        recepturaFrame.setVisible(true);
    }//GEN-LAST:event_jItemSlika2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        otvoriGlavnuSliku();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        otvoriGlavnuSliku2();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (preletiFrame != null) {
            preletiFrame.dispose();   
        }
        preletiFrame = new PreletiFrame(pogon);
        preletiFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (otpremaFrame != null) {
            otpremaFrame.dispose();   
        }
        otpremaFrame = new PregledOtpremaFrame(otpremaDb, sarzaDb);
        otpremaFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    public void otvoriGlavnuSliku(){
        if (glavnaSlike1Frame != null) {
            glavnaSlike1Frame.dispose();   
        }
        glavnaSlike1Frame = new InternalFrameGlavnaSlika1(pogon, RecepturaDb, new Image());
        jDesktopPane1.add(glavnaSlike1Frame);
        glavnaSlike1Frame.show();
        glavnaSlike1Frame.setLocation(xOsa, yOsa);
        glavnaSlike1Frame.timerStart();
    }
    
    public void otvoriGlavnuSliku2(){
       if (glavnaSlike2Frame != null) {
            glavnaSlike2Frame.dispose();   
        }
        glavnaSlike2Frame = new InternalFrameGlavnaSlika2(pogon, RecepturaDb, otpremaDb, proracunKomponenti, new Image());
        jDesktopPane1.add(glavnaSlike2Frame);
        glavnaSlike2Frame.show();
        glavnaSlike2Frame.setLocation(xOsa, yOsa);
        glavnaSlike2Frame.timerStart();
    }
    
     public static void showOnScreen(int screen, JFrame frame) {
        //za prikaz na displeju kod multidispleja
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gd = ge.getScreenDevices();
        if (screen > -1 && screen < gd.length) {
            frame.setLocation(gd[screen].getDefaultConfiguration().getBounds().x, frame.getY());
        } else if (gd.length > 0) {
            frame.setLocation(gd[0].getDefaultConfiguration().getBounds().x, frame.getY());
        } else {
            throw new RuntimeException("No Screens Found");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ItemParametriZbirni;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jItemSlika2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
    private final int yOsa = 0;
    private final int xOsa = -5;
    private final int yOsaHeder = 0;
    private final int xOsaHeder = 170;
    
    private final Pogon pogon;
    private final ProracunBrSarzi proracunKomponenti;
    
    private InternalFrameGlavnaSlika1 glavnaSlike1Frame = null;
    private InternalFrameGlavnaSlika2 glavnaSlike2Frame = null;
    private RecepturaFrame recepturaFrame = null;
    private ZbirniParametriFrame zbirniParametri = null;
    private PreletiFrame preletiFrame = null;
    private PregledOtpremaFrame otpremaFrame = null;
        
    private final RecepturaService RecepturaDb;
    private final OtpremaService otpremaDb;
    private final ZbirniParametriService zbirniParametriDb;
    private final SarzaService sarzaDb;
}
